### ISSUE TITLE
Adding a new implementation to the supported languages list

### ISSUE THREAD

**Issue by polvalente** [grpc/grpc.io#1008]
Are there any criteria for adding a new language to the [Supported Languages ](https://grpc.io/docs/languages/) list?
The implementation at https://github.com/elixir-grpc/grpc could be a candidate, but I don't know if there is a test suite or something similar that needs to be met.

**Comment by yashykt** [comment]
I believe grpc.io only covers stuff in https://github.com/grpc

**Comment by polvalente** [comment]
That makes sense :)
If that's the case, we can go ahead and close this issue
