### ISSUE TITLE
Broken link in C++ API reference page

### ISSUE THREAD

**Issue by AnthonyWharton** [grpc/grpc.io#105]
**Describe the bug**
The following link in the C++ documentation is broken: https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context_base.html

**To Reproduce**
Go to: https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context_base.html
Recieve a 404.

**Expected behavior**
The `ServerContextBase` documentation loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/7091722/75679424-803c5780-5c87-11ea-8378-ef6acb96ac5b.png)

**Additional context**
This is especially annoying as many methods in [`ServerContext`](https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context.html) are inherited from here and I can't access the documentation through your site.

**Comment by lucperkins** [comment]
@AnthonyWharton On which page are you seeing the broken link?

**Comment by AnthonyWharton** [comment]
As mentioned in the issue, ServerContext contains links to ServerContextBase which are broken. https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context.html

I can’t be sure that is the only location though - it seems like a doxygen page is just missing.

**Comment by chalin** [comment]
@AnthonyWharton or @lucperkins - this issue should be transferred to https://github.com/grpc/grpc/issues.

Luc to you have the permissions to do the transfer? I don't have sufficient permissions over grpc/grpc. If you don't then Anthony will need to reopen the issue over there.

Btw, @AnthonyWharton, it would be helpful to include a link to the page that contains the broken link.

**Comment by AnthonyWharton** [comment]
@chalin I can transfer that issue over, assuming it is an issue with the doxygen generation then and not to do with the site.

And without trying to be too defensive, I'd just like to mention once again that I did give an example of a page with the broken link in the "Additional Context" section in the original issue.  I will admit this could have been made clearer though.

**Comment by chalin** [comment]
@AnthonyWharton thanks for transferring the issue (and pointing out the "Additional context" that I missed! Once you have completed the transfer, please include a cross reference in this issue and then close it.
