### ISSUE TITLE
grpcio-tools depends not on the latest version of protobuf library

### ISSUE THREAD

**Issue by rkhudov** [grpc/grpc.io#1050]
grpcio-tools 1.48.1 depends on protobuf<4.0dev and >=3.12.0

But there is exist the protobuf with version 4.21.6. Link: https://pypi.org/project/protobuf/
Could you pls update protobuf version

**Comment by gnossen** [comment]
This was resolved by grpcio-tools 1.49.0, but 1.49.0 had to be yanked for unrelated reasons. 1.49.1 will be released soon with support for protobuf 4.X.X.

In the future, please direct questions like these to the gRPC C++/Python repo [here](https://github.com/grpc/grpc).
