### ISSUE TITLE
python_generator.h

### ISSUE THREAD

**Issue by nandhasa1986** [grpc/grpc.io#1081]
I am getting the below error:
CentOS7, gcc - 7.3.1, protoc -- libprotoc 3.21.6

In file included from /home/nandha/grpcServer/grpc/src/compiler/python_generator.cc:19:0:
/home/nandha/grpcServer/grpc/src/compiler/python_generator.h:47:12: error: ‘uint64_t grpc_python_generator::PythonGrpcGenerator::GetSupportedFeatures() const’ marked ‘override’, but does not override
   uint64_t GetSupportedFeatures() const override;
            ^~~~~~~~~~~~~~~~~~~~
/home/nandha/grpcServer/grpc/src/compiler/python_generator.cc: In member function ‘uint64_t grpc_python_generator::PythonGrpcGenerator::GetSupportedFeatures() const’:
/home/nandha/grpcServer/grpc/src/compiler/python_generator.cc:883:10: error: ‘FEATURE_PROTO3_OPTIONAL’ was not declared in this scope
   return FEATURE_PROTO3_OPTIONAL;
          ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/grpc_plugin_support.dir/build.make:147: CMakeFiles/grpc_plugin_support.dir/src/compiler/python_generator.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/host_port.cc.o
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/mpscq.cc.o
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/stat_posix.cc.o
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/stat_windows.cc.o
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/strerror.cc.o
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/tchar.cc.o
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/thd_posix.cc.o
[  4%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/thd_windows.cc.o
[  5%] Building CXX object CMakeFiles/gpr.dir/src/core/lib/gprpp/time_util.cc.o
make[1]: *** [CMakeFiles/Makefile2:686: CMakeFiles/grpc_plugin_support.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Linking CXX shared library libgpr.so
[  5%] Built target gpr
make: *** [Makefile:171: all] Error 2

**Comment by nandhasa1986** [comment]
cmake ../.. -DgRPC_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DgRPC_ABSL_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_RE2_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DBUILD_SHARED_LIBS=ON

used the above command

**Comment by nimf** [comment]
This is a repo for gRPC website contents, not gRPC itself. Please ask your question in [grpc-io mailing list](https://groups.google.com/g/grpc-io) or on stackowerflow.
