### ISSUE TITLE
protobuf-maven-plugin supports jakarta instead of deprecated javax.annotation

### ISSUE THREAD

**Issue by Shulamite** [grpc/grpc.io#1113]
protobuf-maven-plugin generated code uses deprecated javax.annotation:
@javax.annotation.Generated

This doesn't compile when we use jakarta modules.

**Comment by ejona86** [comment]
This is unrelated to `protobuf-maven-plugin` and this repository `grpc.io`.

The solution here is "follow our documentation and add a provided dependency on org.apache.tomcat:annotations-api:6.0.53." Yes it isn't jakarta, but everything _works_, at least to our knowledge. https://github.com/grpc/grpc-java/issues/9179 has the discussion about swapping to something else, which needs someone to do investigation work of the Java ecosystem.
