### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by skartikey** [grpc/grpc.io#1124]
I am trying to follow [Quick start guide for C++](https://grpc.io/docs/languages/cpp/quickstart/) on mac. 

commands present in [Build and install gRPC and Protocol Buffers](https://grpc.io/docs/languages/cpp/quickstart/#build-and-install-grpc-and-protocol-buffers) is failing as `make` is not supported anymore. 

Error:
```
 ~/code/grpc  #v1.54.0  make install                                                                                                                          
Installing via 'make' is no longer supported. Use cmake or bazel instead.
Please consult BUILDING.md to get more information.
make: *** [stop] Error 1
```

**Comment by XuanWang-Amos** [comment]
@yashykt looks like we should update the documentation?

**Comment by yijiem** [comment]
I'm pretty sure I have tried this instructions for the v1.56.0 branch recently and it worked for me. @skartikey are you using the makefile generated by cmake?
