### ISSUE TITLE
installing grpc on BlueField-2 DPU 

### ISSUE THREAD

**Issue by mashemat** [grpc/grpc.io#1129]
Hello Everyone, 

I am trying to install grpcio for ubuntu on BlueField-2 SmartNIC. However, while it is trying to building wheel, it waits forever:

Collecting grpcio
  Using cached grpcio-1.54.2.tar.gz (23.5 MB)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... \

What would be the issue here?

Thanks,

**Comment by zasweq** [comment]
@thisisnotapril I think I'm supposed to ping you.
