### ISSUE TITLE
Unknown flag: --go-grpc_opt

### ISSUE THREAD

**Issue by John-zhan** [grpc/grpc.io#1138]
protoc --go_out=. --go_opt=paths=source_relative s--go-grpc_out=. --go-grpc_opt=paths=source_relative ./person/person.proto
My command up here. It's just prompt this. So confused

**Comment by nimf** [comment]
Maybe it's the typo `s--go-grpc_out`? The letter `s` in front.

**Comment by yashykt** [comment]
This is not the right repo for this either. You probably want - https://github.com/grpc/grpc-go?
