### ISSUE TITLE
Python detailed API documentation

### ISSUE THREAD

**Issue by mjovanovic9999** [grpc/grpc.io#1146]
Content text in API documentation overlaps with description. See the problem on the photo

![problem](https://github.com/grpc/grpc.io/assets/73258168/da7de808-fbd0-41f2-b3bc-fc2c6f0fa711)

or on link:

https://grpc.github.io/grpc/python/grpc.html#

The problem persists in Firefox as well as in Brave browser.

**Comment by dfawley** [comment]
Do you know anything about this @gnossen

**Comment by gnossen** [comment]
This should be resolved by https://github.com/grpc/grpc/pull/33908, which will be visible upon the next release.
