### ISSUE TITLE
Kotlin API link is broken

### ISSUE THREAD

**Issue by pavlo-dh** [grpc/grpc.io#1170]
Hi!

The link for Kotlin API (https://grpc.io/docs/languages/kotlin/api/) which can be found on Kotlin page (https://grpc.io/docs/languages/kotlin/) is broken.
It leads to https://javadocs.dev/io.grpc/grpc-kotlin-stub/latest with the following content:

> Error: Page not found
> The requested URL was not found on this server.

**Comment by jamesward** [comment]
The javadocs.dev site should be working again.
