### ISSUE TITLE
 YouTube widget is missing from the homepage

### ISSUE THREAD

**Issue by castrojo** [grpc/grpc.io#1201]
**Issue description**
YouTube widget is missing from the homepage

**Steps to reproduce the issue**
1. Go to grpc.io
2. Scroll down to the bottom
3. Social widgets exist for twitter, the group, and gitter, but not YouTube.

**Expected behavior**
I wanted to check the youtube channel out but it's missing from the front page, but I knew the channel existed and clicked around until I found it on the community page. 

Filing this because when most people see that style of social icon on the front page they assume that's what the project has. 

**Screenshots**

![image](https://github.com/grpc/grpc.io/assets/1264109/c637b408-56e7-4dab-8a4c-b2bedc9bd018)

**Comment by easwars** [comment]
@temawi : Would you know who would be responsible for this?

**Comment by temawi** [comment]
@YifeiZhuang Could you please include a link to the gRPC YouTube channel here?
