### ISSUE TITLE
Documentation: Python API glossary "channel_arguments" points to C header file that doesn't contain relevant information

### ISSUE THREAD

**Issue by paskozdilar** [grpc/grpc.io#1212]
The [Python API glossary for "channel arguments"](https://grpc.github.io/grpc/python/glossary.html#term-channel_arguments) contains a link to a [header file grpc_types.h](https://github.com/grpc/grpc/blob/v1.58.x/include/grpc/impl/codegen/grpc_types.h), but that file does not contain any flags or \[sic\] `grpc_arg_keys`.

I believe that the relevant file is [channel_arg_names.h](https://github.com/grpc/grpc/blob/v1.58.x/include/grpc/impl/channel_arg_names.h).

The documentation should be updated to point to the relevant file.

**Comment by paskozdilar** [comment]
I'd send a PR, but

1) I can't find any reference to `grpc_types` in the repository
2) I can't even build the repository: 
    - running `npm install` gives the following error:
    - `No matching version found for @typescript-eslint/typescript-estree@^4.33.0`

**Comment by gnossen** [comment]
Looks like it's just a bit of bitrot. The channel args have been moved to [this header](https://github.com/grpc/grpc/blob/v1.58.x/include/grpc/impl/channel_arg_names.h).

The source code for these docs actually lives [here](https://github.com/grpc/grpc/blob/74c1de6512cb6f892201eefcef4b89aa684ae109/doc/python/sphinx/glossary.rst#L43).

**Comment by paskozdilar** [comment]
Alright, I'll create the issue / PR there.

Thank you for the quick feedback :)
