### ISSUE TITLE
How big should a single service be?

### ISSUE THREAD

**Issue by mattharrigan** [grpc/grpc.io#123]
Hello,

How big should a single grpc service be? How many rpc's is "too many" in general or as a rough heuristic? What are the typical considerations when deciding what to lump together vs split? I apologize if this is the wrong place to ask these questions. Thank you.

**Comment by chalin** [comment]
Issues in this repo should be specific to the grpc.io site documentation.

For answers to questions like yours, consider posting to the [grpc mailing list](https://groups.google.com/forum/#!forum/grpc-io), or try other venues listed on the [Community](https://grpc.io/community) page.
