### ISSUE TITLE
Quick start, java: enhancing user comprehension and readability by adding comments."

### ISSUE THREAD

**Issue by mohammedyusuf380** [grpc/grpc.io#1244]
**Adding comments and explanatory notes within the code snippets. To enhance readability and understanding for users, 
 Here's an example**

### In Update the server

// Inside HelloWorldServer.java
private class GreeterImpl extends GreeterGrpc.GreeterImplBase {

  @Override
  public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
    #// Create a greeting response for the received request   
    HelloReply reply = HelloReply.newBuilder().setMessage("Hello " + req.getName()).build();
    responseObserver.onNext(reply);
    responseObserver.onCompleted();
  }

  @Override
  public void sayHelloAgain(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
    // Create another greeting response for the received request
    HelloReply reply = HelloReply.newBuilder().setMessage("Hello again " + req.getName()).build();
    responseObserver.onNext(reply);
    responseObserver.onCompleted();
  }
}

### In Update the client 

public void greet(String name) {
  // Log an attempt to greet the user
  logger.info("Will try to greet " + name + " ...");
  
  // Create a request with the user's name
  HelloRequest request = HelloRequest.newBuilder().setName(name).build();
  HelloReply response;
  
  try {
    // Call the 'sayHello' method and handle the response
    response = blockingStub.sayHello(request);
  } catch (StatusRuntimeException e) {
    // Log if the RPC fails
    logger.log(Level.WARNING, "RPC failed: {0}", e.getStatus());
    return;
  }
  
  // Log the greeting received from the server
  logger.info("Greeting: " + response.getMessage());
  
  try {
    // Call the 'sayHelloAgain' method and handle the response
    response = blockingStub.sayHelloAgain(request);
  } catch (StatusRuntimeException e) {
    // Log if the RPC fails
    logger.log(Level.WARNING, "RPC failed: {0}", e.getStatus());
    return;
  }
  
  // Log the additional greeting received from the server
  logger.info("Greeting: " + response.getMessage());
}

By include these comments, which provide light on the objectives of each code block, readers will find it simpler to comprehend how the code in the Jaeger Java example works.

**Comment by eugeneo** [comment]
@thisisnotapril

**Comment by temawi** [comment]
@mohammedyusuf380 If you want to make a PR that adds some comments I'd be happy to review it.

**Comment by mohammedyusuf380** [comment]
Added comments and Raised PR@temawi
