### ISSUE TITLE
Max size

### ISSUE THREAD

**Issue by moghadas76** [grpc/grpc.io#1254]
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (17777780 vs. 4194304)"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50051 {grpc_message:"Received message larger than max (17777780 vs. 4194304)", grpc_status:8, created_time:"2024-02-04T18:24:17.281675969+01:00"}"

**Comment by sergiitk** [comment]
Hey @moghadas76. We do language-specific issue support in language-specific repos. Please, feel free to create your issue in on of the them: [grpc](https://github.com/grpc/grpc) for cpp, python and other wrapped languages, [grpc-java](https://github.com/grpc/grpc-java), [grpc-go](https://github.com/grpc/grpc-go), [grpc-node](https://github.com/grpc/grpc-node).
