### ISSUE TITLE
Website bug report

### ISSUE THREAD

**Issue by jarrodcolburn** [grpc/grpc.io#1270]
**Issue description**
Isn't CoreOS discontinued?

**Steps to reproduce the issue**
1. Go to website at "Who's using" https://grpc.io/about/#whos-using-grpc-and-why

**Expected behavior**
I'd expect to see current (not discontinued) projects that use gRPC. 

**Screenshots**
![grpc io_about_](https://github.com/grpc/grpc.io/assets/16673615/a6903253-e1d1-4c9f-89e1-746af0fb57f1)

**Comment by yashykt** [comment]
@thisisnotapril

**Comment by jarrodcolburn** [comment]
Sorry, hope this isn't coming off as a gripe, I would love to see `grpc` dominate (and see less REST). But I think a part of that is making it seem relevant and exciting. And linking it to outdated products, like CoreOS, give it the appearance of being semi-irrelevant by proxy.

**Comment by YifeiZhuang** [comment]
@jarrodcolburn  thanks a lot for reporting the issue.
@thisisnotapril coreOS is outdated, could you help assign someone to remove/replace it?
