### ISSUE TITLE
PHP gRPC server

### ISSUE THREAD

**Issue by CViniciusSDias** [grpc/grpc.io#1283]
The documention states that it's impossible to create a gRPC server with PHP (https://grpc.io/docs/languages/php/quickstart/#get-the-example-code), but it is perfectly possible in several different ways. One (very easy and simple) example:

https://hyperf.wiki/3.1/#/en/grpc

**Comment by temawi** [comment]
@stanley-cheung do you have context on this project and if the PHP documentation should be updated?

**Comment by stanley-cheung** [comment]
Archived discussion from a long time ago: https://groups.google.com/g/grpc-io/c/F3IyYaI_6S0/m/KaFhYXksAQAJ

**Comment by CViniciusSDias** [comment]
I don't understand how this discussion closes the documentation issue. 🤔 

The documentation states that is not possible to create a gRPC server but there are even PHP frameworks that have examples in their documentation. I have gRPC servers written in PHP running in prod.

Did I miss something?
