### ISSUE TITLE
`make serve` broken on master

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc.io#146]
`make serve` does not currently work on master:

```
rbellevi@rbell:~/Dev/grpc.io$ make serve
hugo server \
        --buildDrafts \
        --buildFuture \
        --disableFastRender
Built in 192 ms
Error: Error building site: TOCSS: failed to transform "sass/style.sass" (text/x-sass): resource "sass/sass/style.sass_5538683f21764355e16f4f866a5e0357" not found in file cache
make: *** [Makefile:9: serve] Error 255
rbellevi@rbell:~/Dev/grpc.io$ hugo version
Hugo Static Site Generator v0.67.1-4F44227B linux/amd64 BuildDate: 2020-03-15T19:31:42Z
```

d721e7c2d028a5369d9ffe840ac6f65015638940 appears to be the first bad commit:

```
git bisect start master 599c577dbd714eedcd3c83a52099adedc3380b98
git bisect run bash -c 'timeout -s INT 2 make serve; [ "$?" == "124" ]'
```

I'm also unable to test changes via `make docker-serve`, meaning we currently have no ability to test out changes to `grpc.io`.

CC @lucperkins 
CC @chalin 
CC @thisisnotapril

**Comment by gnossen** [comment]
I'm now seeing there's a preview available on PRs. Very nice. That makes this issue much less urgent. Could be an environmental issue on my end, but it's still probably something that we should address.

**Comment by chalin** [comment]
Hi Richard. Hmm, `make serve` from master@HEAD generates the site just fine for me. Maybe try `make clean` and then try to serve again?

**Comment by gnossen** [comment]
I did `make clean` and `git clean -xdf`. Nothing doing. Hugo version:

```
rbellevi@rbell:~/Dev/grpc.io$ hugo version
Hugo Static Site Generator v0.67.1-4F44227B linux/amd64 BuildDate: 2020-03-15T19:31:42Z
```

**Comment by chalin** [comment]
You need the extended version of hugo.

**Comment by gnossen** [comment]
That fixes the problem! Thanks!

**Comment by gnossen** [comment]
PR to automate the check: https://github.com/grpc/grpc.io/pull/150

**Comment by chalin** [comment]
FYI I've updated the README (#149) to avoid this problem in the future.

**Comment by gnossen** [comment]
Thanks for the speedy response! Great work on the site!
