### ISSUE TITLE
Layout of FAQ headers is broken

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc.io#15]
![image](https://user-images.githubusercontent.com/9939684/56893634-a13e8580-6a83-11e9-9aa7-f5b6aaa7c866.png)

**Comment by cjyabraham** [comment]
I can't reproduce this.  What browser are you using?  Here is what I see:
![Screen Shot 2019-04-29 at 9 26 35 PM](https://user-images.githubusercontent.com/463160/56902939-82f97980-6ac5-11e9-803a-08202a2a06dd.png)

**Comment by jtattermusch** [comment]
Just make your screen wider, then you'll experience the problem. I'm using chrome.

**Comment by lucperkins** [comment]
@jtattermusch Fixed! Thanks for reporting.
