### ISSUE TITLE
Can't access language-specific pages on mobile

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#168]
For example, from the main [Quick Start](https://grpc.io/docs/quickstart) page, there is no in-page link to language specific quick starts.

Related: #169

**Comment by chalin** [comment]
cc @lucperkins

**Comment by chalin** [comment]
My suggestion is that we start with the [QuickStart section](https://grpc.io/docs/quickstart/), and add the list of the section's pages [similarly to what the old site did](https://grpc.github.io/docs/quickstart/):

> <img src="https://user-images.githubusercontent.com/4140793/82596244-fc528700-9b74-11ea-9a63-0199b0a8a6d2.png" width=400>

**Comment by lucperkins** [comment]
Ah, gotcha. No problemo.

**Comment by chalin** [comment]
FYI, #238 fixes this issue (allowing access to the language-specific pages from mobile too), although that wasn't the main intent of the PR.

As I mention in #238, I'm aware that #238 isn't using list templates. I'd like to see what the team has to say about the (generated-)content changes of #238 before switching to list templates in a followup PR.
