### ISSUE TITLE
May I know the RDMA support for gRPC

### ISSUE THREAD

**Issue by gwnet** [grpc/grpc.io#187]
can I use gRPC over RDMA to get better performance for RDMA HW. is there any branch is working on this kind of support? I can test it out?

**Comment by chalin** [comment]
Hi. The issues over this repo are used to report problems or request enhancements to the grpc.io website. To ask questions about gRPC itself, use one of the venues in the [Community](https://grpc.io/community/) page. For example, you could post your question on the Mailing list or the Gitter channel. Good luck!
