### ISSUE TITLE
Build instructions are broken

### ISSUE THREAD

**Issue by madari** [grpc/grpc.io#19]
### What did you do?

As per https://github.com/grpc/grpc/blob/master/BUILDING.md#unix:

`$ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc`

### What did you expect to see?
 
I expected `curl -L https://grpc.io/release` to return the version/branch, which could then be checked out.
 
### What did you see instead?
 
`curl -L https://grpc.io/release` returns a 404.

**Comment by lucperkins** [comment]
The `curl` command once again works as expected with the merger of #20. Closing.
