### ISSUE TITLE
Community meeting link refers to private doc

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#192]
Excerpt from **Community meeting > [Community meetings](https://grpc.io/community/#community-meetings)**:
> Meeting information and notes can be found at [bit.ly/grpcmeetings](https://bit.ly/grpcmeetings).

Clicking on the link gives to a "You need permission" message. The document should be open to the public.

**Comment by srini100** [comment]
I don't have permission either. @thisisnotapril  might be the owner.

**Comment by chalin** [comment]
The document is now accessible, thanks @thisisnotapril! 🎉
