### ISSUE TITLE
Error Handling page has raw markdown link in description

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.io#199]
At https://grpc.io/docs/guides/error/ , we see:
> This page describes how gRPC deals with errors, including gRPC's built-in error codes. Example code in different languages can be found \[here](https://github.com/avinassh/grpc-errors).

I thought it'd be an easy syntax fix, but looking at the page https://github.com/grpc/grpc.io/blob/master/content/docs/guides/error.md it looks like the problem is that markdown is unsupported in the description.

It's unclear if it should use HTML \<a> tags, or whether the link just needs to move into the page's body.

**Comment by lucperkins** [comment]
I can add Markdown support for descriptions
