### ISSUE TITLE
Add link to gRPC case studies hosted on cncf.io

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#206]
https://www.cncf.io/case-studies?_sft_lf-project=grpc

cc @caniszczyk @zacharysarah - it would be great if the [case studies hosted on cncf.io](https://www.cncf.io/newsroom/case-studies/) had a publication date at the top of the page. By looking at the page source, I can see from some metadata fields that the [Netflix case study](https://www.cncf.io/case-study/netflix/) was likely published in August 2019, but it would be great to have that information be more easily accessible. Should I open an issue over cncf.io?

**Comment by zacharysarah** [comment]
@chalin An issue sounds good. 👍

**Comment by chalin** [comment]
@zacharysarah 

> An issue sounds good.

Over which repo should I open the issue?
 1. https://github.com/cncf/cncf.io
 2. https://github.com/cncf/wordpress-site
 3. Another repo

> I'm not sure whether adding a publication date is a good idea or not; what's the specific goal for visitors?

The main goal is for the reader to be able to assess how fresh the article is. For example, as a reader, I'd be more inclined to spend time reading about a 2019 case study than one that was published in 2009. If I come across a stated limitation in a 2017 article, I might have hope that the limitation has been addressed, and so on.

**Comment by chalin** [comment]
Waiting on https://github.com/cncf/cncf.io/issues/104 :)
