### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by dexception** [grpc/grpc.io#21]
> pip3 install grpc --ignore-installed
> Collecting grpc
>   Using cached https://files.pythonhosted.org/packages/dd/63/e25fa1e7dbbd44ae4d2d5ceb1bfef517849c854795e73d01bfd3d250a8b1/grpc-0.3-19.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-x8_v1sko/grpc/setup.py", line 7, in <module>
>         version_tuple = __import__('grpc').VERSION
>       File "/tmp/pip-install-x8_v1sko/grpc/grpc/__init__.py", line 6, in <module>
>         from .rpc import *
>       File "/tmp/pip-install-x8_v1sko/grpc/grpc/rpc.py", line 141
>         except OSError, ex:
>                       ^
>     SyntaxError: invalid syntax
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-x8_v1sko/grpc/
>

**Comment by jamessmith90** [comment]
+1 I am also facing the same issue.

**Comment by MrMajorThorburn** [comment]
+1 and me too
