### ISSUE TITLE
Navigation sidebar cannot easily be scrolled

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.io#217]
I was on https://grpc.io/docs/tutorials/basic/dart/ . I noticed that the navigation sidebar was cut off. So I tried to scroll to see more options, and couldn't. Instead, I have to scroll to the very end of the page for more of the sidebar to be visible.

This makes the sidebar navigation mostly useless for languages lower on the list.

![image](https://user-images.githubusercontent.com/2811396/81106699-e6816880-8eca-11ea-9e60-8f752107234a.png)

----------------------

![image](https://user-images.githubusercontent.com/2811396/81106817-103a8f80-8ecb-11ea-8850-7bd70fa9765f.png)

**Comment by chalin** [comment]
I would prefer having a page design where the page TOC appears elsewhere, either in a right-side nav and/or inline at the top of the page (e.g., on narrow displays). For an example of this, see https://flutter.dev/docs.

**Comment by ejona86** [comment]
I prefer inline TOC as well. I am always confused when using TOC-on-the-side-mixed-in-with-nav since it isn't clear what is within-this-page vs somewhere else.

But even with the sidebar just having normal navigation, it is too long when the list of languages is expanded and cannot be scrolled.

![image](https://user-images.githubusercontent.com/2811396/81117789-94e1d980-8edc-11ea-9bf3-d9eb9b1ba23d.png)

**Comment by chalin** [comment]
> I prefer inline TOC as well ...

Will be tracked via #231

**Comment by ejona86** [comment]
It looks like this was vastly improved, but the navigation is still being cut off on the bottom. There should be Samples and Presentations visible on the left. I have to scroll to the bottom of the page (not sidebar) to see them.

![image](https://user-images.githubusercontent.com/2811396/86028609-f14a0c80-b9e6-11ea-871e-9d7dc3ff5e58.png)

**Comment by chalin** [comment]
> It looks like this was vastly improved, but the navigation is still being cut off on the bottom. 

Yes, though I had opened #295 to track the remaining issue(s). Are you ok with us using #295?

**Comment by ejona86** [comment]
Ah. It sounded like that was more related to small screens and mobile improvements, and that it was going to swap away from the sidenav for those scenarios. Here I'm seeing it cutoff with a Chrome window of 1134x994.

**Comment by chalin** [comment]
Ok, we can stick to this issue. I'll close #295 -- here's its opening-comment text:

> - Context:
>   - https://github.com/grpc/grpc.io/pull/264#issuecomment-644735492
>   - https://github.com/grpc/grpc.io/pull/264#issuecomment-645556413
> - Followup to #217 and #264.
