### ISSUE TITLE
Update link to gRPC-Kotlin API reference docs

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#218]
The gRPC-Kotlin API reference docs will be accessible from another URL once https://github.com/grpc/grpc-kotlin/issues/74 is addressed.

**Comment by jamesward** [comment]
This is good to go: https://javadocs.dev/io.grpc/grpc-kotlin-stub/latest/

**Comment by chalin** [comment]
Thanks for confirming James. I'll update this very soon (I need to wrap up a larger PR first).
