### ISSUE TITLE
Website bug report

### ISSUE THREAD

**Issue by pedrosousagrilo** [grpc/grpc.io#220]
https://github.com/grpc/grpc.io/blame/master/content/docs/guides/benchmarking.md#L34
**Issue description**
Broken URL

**Comment by chalin** [comment]
The Benchmarking page is hosted here: https://grpc.io/docs/guides/benchmarking, and the image link (which you refer to in line 34 of the markdown source) is displaying fine AFAICT:

> ![image](https://user-images.githubusercontent.com/4140793/81675216-728c1680-941c-11ea-9a76-59bafd1ba398.png)

I'll close this issue for now, but if you still believe that there is a broken link, add a comment to this issue with more details.
