### ISSUE TITLE
The location of pb file generated in quickstart(go) is incorrect

### ISSUE THREAD

**Issue by guce** [grpc/grpc.io#236]
**Issue description**
The location of pb file generated in quickstart(go) is incorrect

**Steps to reproduce the issue**
https://grpc.io/docs/quickstart/go/
1. Get the example code
```
$ git clone https://github.com/grpc/grpc-go
```
2. Regenerate gRPC code
```
$ protoc -I helloworld/ helloworld/helloworld.proto --go_out=plugins=grpc:helloworld
```
3. pb file in the wrong location
```
helloworld
├── google.golang.org
│   └── grpc
│       └── examples
│           └── helloworld
│               └── helloworld
│                   └── helloworld.pb.go   <---- 
├── helloworld.pb.go                       <---- 
└── helloworld.proto
```

**Expected behavior**
pb file can be updated correctly

**Comment by chalin** [comment]
Thanks for filing an issue @guce! A fix is on the way (#241).
