### ISSUE TITLE
Running gRPC-web quick start results in HTTP_ERROR

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#269]
Running the gRPC-web quick start results in the following errors:

> ![image](https://user-images.githubusercontent.com/4140793/83928369-8f86e180-a75d-11ea-8e33-d4e005763a37.png)

**Comment by stanley-cheung** [comment]
Just to double check - are those docker images running? Can you run a `docker ps -a` please?

**Comment by chalin** [comment]
Oops, my bad. Was running to many local servers. It's working now.
