### ISSUE TITLE
gRPC web page doesn't link to an API reference

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#275]
There is no link to an API reference in https://grpc.io/docs/languages/web.

@stanley-cheung - if we were to add a link to an API reference, what would that link be?

**Comment by stanley-cheung** [comment]
unfortunately there's none right now - is there some tools we can use to run it over all the .js file in this directory https://github.com/grpc/grpc-web/tree/master/javascript/net/grpc/web as a starting point?

**Comment by chalin** [comment]
I'm not sure, maybe https://github.com/jsdoc/jsdoc? (I haven't generated API reference docs for JS packages before.) Ok, I'll close this for now until we get a user request for it.
