### ISSUE TITLE
Update Go quick-start once cmd/protoc-gen-go-grpc is at v1.0

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#298]
Context: https://github.com/grpc/grpc-go/issues/3688#issuecomment-646337955. We've known that this was coming.

Awaiting next release. It seems like the next release will be 1.31 (with 1.30 being skipped)?

Related:

- [x] Update Go quick start to work with grpc-go v1.30.0-dev.1 or v1.30.0 #306 via #313

**Comment by chalin** [comment]
@dfawley - I don't think that I can update the quick-start page yet, right? That is, we're still required to use `github.com/golang/protobuf/protoc-gen-go@v1.3`. (Also see the question given here: https://github.com/grpc/grpc-go/pull/3453#issuecomment-648291732). Otherwise, if there are updates that _can_ be made to the quick-start page now, let me know what they are, thanks.

**Comment by chalin** [comment]
In #304, the `grpc_go_release_tag` was updated:

```diff
-  grpc_go_release_tag: v1.30.0-dev.1
+  grpc_go_release_tag: v1.30.0
```

I'm going to revert this since the instructions aren't working otherwise.

**Comment by chalin** [comment]
So we're waiting on `cmd/protoc-gen-go-grpc` to be usable and released (if I understand the situation correctly). That is, we're waiting on: https://github.com/grpc/grpc-go/issues/3669

**Comment by BarberEngineering** [comment]
If you found this from the quick start guide - here's the steps to get this working

Do the steps in the guide before this link then:

Get the grpc-go repo
```bash
git clone -b v1.30.0 https://github.com/grpc/grpc-go 
```

Install protoc-gen-go-grpc
```bash
cd grpc-go/cmd/protoc-gen-go-grpc
go install .
```

Now you can use the --go-grpc_out=. switch compiling your program and it will work

**Comment by chalin** [comment]
Link to relevant discussion: https://github.com/grpc/grpc-go/issues/3669#issuecomment-669460274

**Comment by celesteking** [comment]
What if I don't want to clone the example repo and just want to proceed with grpc files generation?

**Comment by celesteking** [comment]
https://grpc.io/docs/languages/go/quickstart/ needs updated with `Service` vs `Server` difference. I just don't get why grpc got released to pkg.go.dev without updating the tutorial.

**Comment by dfawley** [comment]
protoc-gen-go-grpc has still not been released at v1.0.  You should still be using the old codegen tool at github.com/golang/protobuf to produce grpc stubs (per the quick start instructions)

**Comment by ludichrislyts** [comment]
The only way I was able to get the QuickStart helloworld.proto to compile was to change the `protoc` commands to 

> protoc   --go_out=Mgrpc/service_config/service_config.proto=/../../internal/proto/grpc_service_config:.   --go-grpc_out=Mgrpc/service_config/service_config.proto=/../../internal/proto/grpc_service_config:. helloworld.proto

Basically provide the path to the config from the `examples/helloworld` folder and remove the `source_relative` flags. Those commands produced the pb.go files, but it put them in another weird 'helloworld' folder. 
Before 
![image](https://user-images.githubusercontent.com/13628993/92838058-2f728d80-f393-11ea-9315-5cf0d986c63f.png)
After
![image](https://user-images.githubusercontent.com/13628993/92838328-7f515480-f393-11ea-8d73-3f872c268e52.png)

I'm super new to this, not sure if I just missed some critical step or something.

**Comment by dfawley** [comment]
Apologies for the misinformation in my comment yesterday.  We are using the new codegen tool in the quickstart guides, but it has been changed since the instructions were released.

The quickstart guide instructs you to use a previous release of gRPC:
```
$ git clone -b v1.31.0 https://github.com/grpc/grpc-go
```

Make sure you are using this version, and are installing `protoc-gen-go-grpc` from within that tree.

**Comment by dfawley** [comment]
`protoc-gen-go-grpc` has been [released](https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.0.0) (finally! :tada:).  You can get it now as follows:
```
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.0
```

I don't believe any other changes should be required in the quick-start guide.

**Comment by tigerwill90** [comment]
Thank's for the update !

**Comment by chalin** [comment]
Thanks @dfawley, I'll try it out (I usually prefer walking through the entire thing), and then update the quick start by Monday.

**Comment by fabstu** [comment]
What tag is the released version? The last tag is v1.33-dev from 24.08.2020. go get uses tags instead of released versions?

**Comment by dfawley** [comment]
`go get` for the module will install it, per the above command:

```
$ go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.0
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.0.0
go: downloading google.golang.org/grpc v1.30.0-dev.1
go: downloading google.golang.org/protobuf v1.23.0
$ ls -l $GOPATH/bin/protoc-gen-go-grpc
...
```

We have a multi-module repo which can be confusing.  The github release page (also linked above) shows the tag for the release.

**Comment by fabstu** [comment]
I searched for the new tag for `protoc-gen-go-grpc` and its not only named v1.0, but rather `cmd/protoc-gen-go-grpc/v1.0.0`. I didn't see that before. Just writing here so not more people get confused about the tag.
