### ISSUE TITLE
Update Go quick start to work with grpc-go v1.30.0-dev.1 or v1.30.0

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#306]
In #304, the `grpc_go_release_tag` was updated:

```diff
-  grpc_go_release_tag: v1.30.0-dev.1
+  grpc_go_release_tag: v1.30.0
```

I'm going to revert this since the instructions aren't working otherwise. For context, see https://github.com/grpc/grpc.io/issues/298#issuecomment-648302316.

**Comment by dfawley** [comment]
Why don't they work with v1.30.0?

**Comment by chalin** [comment]
Because v1.30.0 has both flavors of the generated files, see https://github.com/grpc/grpc-go/tree/master/examples/helloworld/helloworld:

> ![image](https://user-images.githubusercontent.com/4140793/85435739-ea8a4800-b555-11ea-9d39-e4e0bb4b329d.png)

As a result we run into the problem reported in https://github.com/grpc/grpc-go/issues/3688.

**Comment by chalin** [comment]
Is there something I'm missing, and it _should_ be working with v1.30.0?

**Comment by dfawley** [comment]
Ideally we'd be using the latest release.  But our latest tag has pb.gos generated with the new, still-experimental codegen tool.  Maybe the release instructions should `rm -rf` the generated code files before regenerating?  Another option is we could revert the examples so they are generated using the legacy codegen tool.

**Comment by chalin** [comment]
> Another option is we could revert the examples so they are generated using the legacy codegen tool.

#307 does that.

> Maybe the release instructions should `rm -rf` the generated code files before regenerating?

I can certainly update the quick start to include the `rm` instruction (with a note stating that this is temporary until, say, `cmd/protoc-gen-go-grpc` is officially released as part of `grpc-go`).

Which approach do you prefer?

**Comment by dfawley** [comment]
> #307 does that.

No, I mean the `pb.go`s checked in in the grpc-go repo.

Option 3 would be to use `protoc-gen-go-grpc` at v0.0.

My preference would be to keep these quick start instructions on the latest release and revert #307.  Option 3 does seem like the best idea, actually, given that's the direction we will want people to go once it is released at v1.0.

**Comment by chalin** [comment]
> No, I mean the `pb.go`s checked in in the grpc-go repo.

Right, but that wouldn't help us address the situation are are in right now. By "#307 does that", I meant that by cloning v1.30.0-dev.1, users get example sources that contain `pb.go`s "generated using the legacy codegen tool" only.

> Option 3 would be to use `protoc-gen-go-grpc` at v0.0. ... Option 3 does seem like the best idea, actually

Ok, but then you'll need to give me some guidance on how to update the quick start instructions. If it would be easier, I wouldn't mind hopping onto a call with you. Let me know.

**Comment by chalin** [comment]
@dfawley - PTAL at #313, I think that it is a step forward in the direction that you wanted.

**Comment by dfawley** [comment]
#313 is Option 1.  This is okay.  Option 3 is to use the new codegen tool in `cmd/protoc-gen-go-grpc` to generate the files (exactly as `regenerate.sh` does, so no need to `rm` them first).  This might be a little nicer, but still requires a small disclaimer about the codegen tool not being v1.0 yet.  But #313 works.  So I'm okay with it if you don't want to redo things.  (But we will still ultimately need to update the instructions to use `cmd/protoc-gen-go-grpc` after it is released.)

**Comment by dfawley** [comment]
Oh, and I'm always happy to hop on a chat/call with you to discuss / help.  Feel free to reach out directly any time!

**Comment by chalin** [comment]
Ok, let me explore option 3 and let you know if I have any questions. (Btw, the Hangout invite I sent to you is still pending :))

**Comment by chalin** [comment]
Does `cmd/protoc-gen-go-grpc` support `source_relative`, if so, what option(s) should I use? I seems to be ignoring `--go_opt=paths=source_relative`.

**Comment by dfawley** [comment]
Since it's a different binary, you need to use `go-grpc_opt` as well as `go_out` now.  See https://github.com/grpc/grpc-go/blob/master/regenerate.sh#L60 for an example.

**Comment by chalin** [comment]
@dfawley - see #319 for option 3.
