### ISSUE TITLE
Android Java quick start: "Could not find any version that matches io.grpc:grpc-core:[1.30.2]"

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#317]
@ejona86 @voidzcy: in working through the [Android Java Quick Start > Run a gRPC application](https://grpc.io/docs/languages/android/quickstart/#run-a-grpc-application), I'm hitting the following issue on step 3:

```console
helloworld > ../../gradlew installDebug

> Configure project :app
The com.google.protobuf plugin was already applied to the project: :app and will not be applied again after plugin: android
Checking the license for package Android SDK Build-Tools 28.0.3 in /Users/chalin/Library/Android/sdk/licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.
Installing Android SDK Build-Tools 28.0.3 in /Users/chalin/Library/Android/sdk/build-tools/28.0.3
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.
Checking the license for package Android SDK Platform 27 in /Users/chalin/Library/Android/sdk/licenses
License for package Android SDK Platform 27 accepted.
Preparing "Install Android SDK Platform 27 (revision: 3)".
"Install Android SDK Platform 27 (revision: 3)" ready.
Installing Android SDK Platform 27 in /Users/chalin/Library/Android/sdk/platforms/android-27
"Install Android SDK Platform 27 (revision: 3)" complete.
"Install Android SDK Platform 27 (revision: 3)" finished.
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find any version that matches io.grpc:grpc-core:[1.30.2].
     Versions that do not match:
       - 1.30.1
       - 1.30.0
       - 1.29.0
       - 1.28.1
       - 1.28.0
       - + 67 more
     Required by:
         project :app > io.grpc:grpc-okhttp:1.30.2

...

BUILD FAILED in 33s
1 actionable task: 1 executed
```

Actually, before running that step I set `ANDROID_HOME`:

```console
$ export ANDROID_HOME=/Users/chalin/Library/Android/sdk
```

otherwise I was making even less progress.

Any idea why it isn't finding `io.grpc:grpc-core` v1.30.2?

**Comment by creamsoup** [comment]
this is happening because jcenter haven't received `1.30.2` yet. It falls back to maven central, so it appears to be working fine for the most part. when it comes to finding a version, it doesn't fall back since outdated version map exists.

can you add `mavenCentral()` to repository, before `jcenter()`? 

```
repositories {
  mavenCentral();
}
```

**Comment by voidzcy** [comment]
We may just wait and let jcenter picks it up. Android Studio users [may not like mavenCentral](https://stackoverflow.com/questions/24852219/android-buildscript-repositories-jcenter-vs-mavencentral).

**Comment by ejona86** [comment]
@creamsoup, that is our code:
https://github.com/grpc/grpc-java/blob/e9ea70935b91e69a5ebc21765c06a895dae6f523/examples/android/helloworld/build.gradle#L19-L21

Note that google() there is the Android Google repo, not the Google Maven Central mirror. So it looks like the Android example is broken any time jcenter is slow to update (which is common).

**Comment by ejona86** [comment]
We've seen it take months to update jcenter, and us needing to file tickets for individual files, one-by-one. The only "solution" I've heard is for us to publish on jcenter and have jcenter publish to Maven Central. But I'm not going to swap us to jcenter just because jcenter is frequently broken.

**Comment by ejona86** [comment]
Maybe for now we should swap to exposing a different grpc-java version for the Android example vs the normal example?

**Comment by chalin** [comment]
> Maybe for now we should swap to exposing a different grpc-java version for the Android example vs the normal example?

I don't mind implementing this, but if we eventually "merge" the Android Java and the (non-Android) Java pages (such as the quick start), that could get messy. (Not that we've decided to merge them yet, but it is being discussed.)

I'm calling it a day. Let me know which solution you prefer. (And thanks for the quick feedback!)

**Comment by chalin** [comment]
Which link(s) can I use to see the versions of grpc packages on jcenter?

On other site's that I've worked on, we pull the latest package version dynamically (when a site page is viewed). That avoids situations like these. What do you think of using such a feature?

**Comment by ejona86** [comment]
Hmm... Yeah, that could get messy. How about we just add mavenLocal to our Android example with a comment of `JCenter has taken over a year to update in the past. We can't wait on it. https://github.com/grpc/grpc-java/issues/5782`.

**Comment by ejona86** [comment]
@chalin, unfortunately JCenter will update some of the files/artifacts but not others. It's just broken.

**Comment by voidzcy** [comment]
Or we just add `mavenCentral()` to android examples. Android Studio users who care about the indexing issue definitely know what is happening and would remove `mavenCentral()`. We can put a note on it.
