### ISSUE TITLE
Benchmarks dashboard is empty

### ISSUE THREAD

**Issue by davidgengenbach** [grpc/grpc.io#337]
**Issue description**
When visiting the links on the [Benchmarking site](https://grpc.io/docs/guides/benchmarking/), no benchmark data is shown.

**Steps to reproduce the issue**
1. Go to https://grpc.io/docs/guides/benchmarking/
2. Click on "Multi-language performance dashboard @latest_release (lastest available stable release)"
3. Wait for page to finish loading
4. Observe empty graphs ("No data available")

**Expected behavior**
The benchmark results should be shown.

**Screenshots**
![Screenshot_2020-07-04_23-09-31](https://user-images.githubusercontent.com/2621491/86521016-71d79580-be4b-11ea-9f91-5d1bfffc595e.png)

**Desktop (if relevant):**
 - OS: Debian GNU/Linux 10 (buster)
 - Browser: **Chrome** (Version 83.0.4103.116 (Official Build) (64-bit)) and **Firefox** (68.10.0esr (64-bit))

**Comment by chalin** [comment]
Hi @davidgengenbach, thanks for filing an issue!

This is a known problem that is being tracked at https://github.com/grpc/grpc/issues/23297.

I'll add a note to the benchmarking page so that others will know.

**Comment by chalin** [comment]
See #338
