### ISSUE TITLE
Web feed

### ISSUE THREAD

**Issue by mfulton26** [grpc/grpc.io#34]
I cannot find a URL for an RSS or Atom feed to subscribe to for your blog. Please advise.

https://grpc.io/feed used to work but no longer does. Thank you.

**Comment by lucperkins** [comment]
@mfulton26 Thanks for submitting! An RSS feed has not been added at https://grpc.io/feed.xml and linked on the blog.

**Comment by mfulton26** [comment]
Thanks!
