### ISSUE TITLE
Dart: quick start/tutorial say to go to "examples" (plural) but "example" (singular) is in grpc-dart

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc.io#355]
**Steps to reproduce the issue**
1. Go to https://grpc.io/docs/languages/dart/quickstart/ 
2. Scroll to where it says `cd grpc-dart/examples/helloworld` (examples with an s)
3. Compare to https://github.com/grpc/grpc-dart/tree/master/example (example without an s)

**Comment by chalin** [comment]
Thanks for catching that!
