### ISSUE TITLE
Drop /docs/quickstart and /docs/tutorials pages

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#360]
- These pages were kept temporarily to allow site users to get used to the new language-based organization. 
- Followup to #359 
- Contributes to #249

**Comment by chalin** [comment]
A point of discussion could be which targets to use; [/docs/languages](https://grpc.io/docs/languages/) seems like a reasonable target. Thoughts @ejona86 @mjpitz @jtattermusch @thisisnotapril?

**Comment by ejona86** [comment]
/docs/languages seems most appropriate. (I'm assuming we're talking about what redirect should be used when we remove the pages.)

**Comment by chalin** [comment]
> I'm assuming we're talking about what redirect should be used when we remove the pages.

Right

**Comment by mjpitz** [comment]
Could we remove the links to the pages, but then keep the pages around for any links that are out there? I could see us re-designing those pages to just be a table of languages. When you click one, it brings you to the proper location.

From a content perspective, there wouldn't be any direct links to the pages anymore, but they would exist for users with links. You could probably even flag them with `noindex,nofollow` so they don't get picked up in search engines anymore. This way, we don't need to worry about 301'ing the page properly. Any link that exists in the wild will continue to function, and users will just be presented with the simple choice to pick their language.

**Comment by chalin** [comment]
>  flag them with `noindex,nofollow` 

I've moved this suggestion to its own issue: #546.

**Comment by chalin** [comment]
Also see this followup issue: #548

**Comment by chalin** [comment]
Given that we've addressed #546 and #548, I'll close this issue for now. If anyone objects, add a comment or reopen the issue. Thanks again for the suggestions @mjpitz!
