### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#370]
GitHub now has support for "early adopters", see https://github.com/github/renaming. I'll use this issue to document the steps.

I mainly followed a variant of [Git: Renaming the "master" branch](https://dev.to/rhymu8354/git-renaming-the-master-branch-137b) by @rhymu8354 -- thanks for the article!

---

Here are the steps I followed (parts are shown as a console transcript):

 1. Rename `master` to `main` and push to all remotes:

    ```console
    $ pwd
    /some/path/git/grpc.io

    $ git remote -v
    origin	https://github.com/chalin/grpc.io.git (fetch)
    origin	https://github.com/chalin/grpc.io.git (push)
    upstream	https://github.com/grpc/grpc.io.git (fetch)
    upstream	https://github.com/grpc/grpc.io.git (push)

    $ git branch
    * master

    $ git branch -m master main

    $ git branch
    * main

    $ git push -u upstream main
    Total 0 (delta 0), reused 0 (delta 0)
    remote:
    remote: Create a pull request for 'main' on GitHub by visiting:
    remote:      https://github.com/grpc/grpc.io/pull/new/main
    remote:
    To https://github.com/grpc/grpc.io.git
    * [new branch]      main -> main
    Branch 'main' set up to track remote branch 'main' from 'upstream'.

    $ git push -u origin main
    Total 0 (delta 0), reused 0 (delta 0)
    remote:
    remote: Create a pull request for 'main' on GitHub by visiting:
    remote:      https://github.com/chalin/grpc.io/pull/new/main
    remote:
    To https://github.com/chalin/grpc.io.git
    * [new branch]      main -> main
    Branch 'main' set up to track remote branch 'main' from 'origin'.
    ```

 2. On [GitHub](https://github.com):

     1. Go to the `origin` repo and change the default branch to `main`
     2. Go to the `upstream` repo:
         1. Change the default branch to `main`
         2. Change the branch protection rules so that they apply to `main`, if you
          had that in place for `master` before

 3. Login to [app.netlify.com](https://app.netlify.com).

     1. Under **Build & deploy** >> **Deploy contexts**:
        rename the **production branch** to `main`.
     2. Save your changes.
     3. Double check to ensure that Netlify hasn't added `master` as a **Branch deploy**.

 4. Delete `master` from all remotes:

    ```console
    $ git push origin --delete master
    To https://github.com/chalin/grpc.io.git
    - [deleted]         master

    $ git push upstream --delete master
    To https://github.com/grpc/grpc.io.git
    - [deleted]         master

    $ git remote set-head upstream -a
    upstream/HEAD set to main

    $ git remote set-head origin -a
    origin/HEAD set to main
    ```

 5. Cleanup website content, layouts and scripts. For example:

     1. I created a `branch` parameter in `config.yaml` for use in templates.
     2. Renamed `master` to `main` in `README.md` and in the template that links
        to page sources in GitHub.

See @rhymu8354's article for instructions explaining how to rename `master` if you have a clone of this repo. If you have a clone of a fork, you'll need an extra few steps along the lines of what is done above.

**Comment by chalin** [comment]
cc @zacharysarah @celestehorgan @caniszczyk

**Comment by celestehorgan** [comment]
As far as I can tell @chalin this is good to go, we'd _temporarily_ break the site deploy (for a matter of minutes/hours). Aside from the branch name change, we'd need to change the deploy branch Netlify looks for in https://app.netlify.com/sites/grpc-io/settings/deploys. Because we can't do both 100% simultaneously, we'd have to accept a small amount of downtime and force rebuild the site after the changeover to ensure Netlify can still find the build branch.

Thoughts? I'm eager to try this out on a smaller-than-k/website repo and see how it goes.

**Comment by chalin** [comment]
@zacharysarah @celestehorgan @caniszczyk - the rename is done. I've documented the steps I following in the opening comment.

While I have access to _a_ Netlify config, it isn't the main one for the site, which @celestehorgan refers to above as https://app.netlify.com/sites/grpc-io/settings/deploys. Apparently, I don't have the permissions to access that config. Can one of you grant me permissions, or finalize the rename? I'm going to reopen this issue until the main Netlify config is updated.

**Comment by mjpitz** [comment]
You'll probably want to leave the `master` branch around until you're certain the CDN has stopped serving stale content since we link to source from the generated site. I purged my CDN and left this around for a week or so before deleting. Also, any unresolved pull requests to the branch will be closed when it's deleted so you'll want to update any PR too.

**Comment by chalin** [comment]
> ... we link to source from the generated site

GitHub does redirects (and I updated the path to sources in #407).

> ... unresolved pull requests

The PR list was empty before I started, but thanks for the tip; it may be useful for others.

**Comment by mjpitz** [comment]
Ah when I did it, I don't think GitHub supported that yet. Very cool!

**Comment by chalin** [comment]
The site is [successfully deploying from `main`](https://app.netlify.com/sites/grpc-io/deploys):

> <img src="https://user-images.githubusercontent.com/4140793/93807652-ecc57680-fc18-11ea-883b-84f0b566e249.png" width=250>

So, we're done! Closing.
