### ISSUE TITLE
Tutorial very hard to understand

### ISSUE THREAD

**Issue by donhuvy** [grpc/grpc.io#445]
The tutorial: https://github.com/grpc/grpc.io/blob/main/content/docs/languages/java/basics.md

I have 7 years experience in Java, I read but don't understand. Let's write it step-by-step manner.

**Comment by dapengzhang0** [comment]
That is the source page of the tutorial. Some links and placeholders are misleading. The rendered page is here https://grpc.io/docs/languages/java/basics/

There is also quick start that is easier to try first: https://grpc.io/docs/languages/java/quickstart/

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by chalin** [comment]
> ... step-by-step manner.

Thanks for the feedback @donhuvy. I do think that there is value in discussing this point at the next Docs WG meeting.
