### ISSUE TITLE
Cleanup footer copyright notices, clarify licences, and more

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#456]
I think that the footer (a screenshot is provided below) needs to be reviewed and updated.

- Cleanup copyright notices, see below for details
- Clarify licences: we have a licence for the "docs" and one for the rest of the site, but only one is mentioned (maybe that's enough).
- A portion (most?) of the footer text can be collapsed into a **Terms of service** page. For an example, see the [dart.dev](https://dart.dev) footer.

cc @zacharysarah @celestehorgan @caniszczyk

## Questions

- Who are the "gRPC Authors"? This seems at best, ambiguous (e.g., are we referring to gRPC package authors?).
  Maybe this should read "Site authors"? I think that the site needs an AUTHORS file (#455).
- Why the two copyright notices? One, should be enough.

## Screenshot

Copyright portion of footer currently reads:

> © gRPC Authors 2020 | Documentation distributed under CC-BY-4.0
>
> © 2020 The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page.

Here's a screenshot:

> ![image](https://user-images.githubusercontent.com/4140793/95865196-63dfbd80-0d34-11eb-8c00-ef1d028dd1b1.png)

**Comment by celestehorgan** [comment]
@chalin This is the standard CNCF/LF project copyright footer. 

For the phrasing of "gRPC Authors", [copyright-notices.md](https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices).

The [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) specify why we use the second line (I assume this has undergone legal approval). As for the "Documentation distributed under.." line, I believe it's because code has a different license agreement than the docs do? 

I imagine @zacharysarah or @caniszczyk have more info on the specifics, but at a high level: this is what we do for every CNCF project, unless they have a unique use case.

**Comment by chalin** [comment]
@celestehorgan - thanks for the background info and the links. A few clarifications:

- Re. "gRPC Authors", my point was more that it would make more sense (IMHO) to use "grpc.io Authors" _and_ to add an AUTHORS file to the website repo.
- I'd expect that we should be able to adhere to the guidelines and least merge the copyright notices, something like this:
  > © 2020 grpc.io Authors and The Linux Foundation

(We can probably wait until the next sync meeting to discuss this, although comments are welcome :))

**Comment by chalin** [comment]
I like the simple recommendation given in https://github.com/cncf/foundation/blob/master/copyright-notices.md#copyright-notices to use "Copyright The XYZ Contributors" w/o (c) or date ranges (if I'm reading that correctly). All repo contributors need to sign a CLA, so the "XYZ" could possibly link to https://github.com/grpc/grpc.io/graphs/contributors.

**Comment by chalin** [comment]
Just an update that this is still relevant, even post docsy-migration.

**Comment by chalin** [comment]
The [CNCF website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) have recently been updated (https://github.com/cncf/foundation/pull/144). PR #716 reworked the gRPC footer (see the PR for a screenshot) and, I believe, the new footer satisfies the updated guidelines. So, this PR was effectively closed by #716.

cc @nate-double-u
