### ISSUE TITLE
Improve Color Contrast 

### ISSUE THREAD

**Issue by cjyabraham** [grpc/grpc.io#5]
Historically, gRPC.io has had a poor color contrast.. we should fix it once and for all with the re-vamp. Ideally, optimize the site for accessibility..

Issue originally from @hsaliak .

**Comment by ejona86** [comment]
Now that the revamp is done, is this fixed?

**Comment by cjyabraham** [comment]
I don't think it has been addressed.  @hsaliak?

**Comment by ejona86** [comment]
I'm going to assume this was done with the revamp. It can be reopened if it isn't the case.
