### ISSUE TITLE
Move .NET page to Platforms?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#511]
Given the changes proposed by #510, it seems interesting to consider moving [gRPC for
.NET](https://grpc.io/docs/languages/csharp/dotnet/) to [Platforms](https://grpc.io/docs/platforms/).

Such a move would be inline with that the Flutter folks are asking for, see [#491: Dart/Flutter under Platforms > Android: which title, etc. to use?](https://github.com/grpc/grpc.io/issues/491).

**Comment by ejona86** [comment]
I don't think this one is as clear. The ".NET platform" isn't the normal definition of "platform" we've been using. It is really another parallel implementation that can be used. I don't feel comfortable making any decisions here. @jtattermusch obviously has the best view of the situation.

**Comment by chalin** [comment]
Thanks for the feedback Eric. 

> The ".NET platform" isn't the normal definition of "platform" we've been using.

Agreed. I made [the same point concerning Flutter too](https://github.com/grpc/grpc.io/issues/491#issuecomment-721766839).

But, I've been warming up to the idea, especially since this seems really important to the Flutter folks. What I have in mind is to change the Platforms page so that it has two sections:

- One section lists the platforms (in the sense that we mean it now, including mobile and web), and
- Another section that lists frameworks and toolkits that support multiple platforms.

Maybe I'll put something together for our next WG meeting.

cc @thisisnotapril @mjpitz

**Comment by chalin** [comment]
Good input on this topic from @ejona86 and @mjpitz during the Docs WG meeting of 2020/11/16. The conclusion is: let's wait before moving the .NET page. I'm going to close this now, it can be reopened if/when the need is felt to revisit this topic.

**Comment by jtattermusch** [comment]
I agree with @ejona86  has said. I don't think .NET is a "platform" in the sense of https://grpc.io/docs/platforms/. It is true that .NET can run on multiple platforms (e.g. Mobile, Windows, Linux), but treating .NET as a platform would be the same as treating Java the same way (because Java also supports both Mobile, Windows, Linux and much more).

**Comment by chalin** [comment]
Thanks for your feedback @jtattermusch 👍
