### ISSUE TITLE
Is gRPC PHP still in beta?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#515]
If you look at the [Official support](https://grpc.io/docs/#official-support), you'll see that PHP is indicated as being in **beta**, that still the case?

> Language | OS | Compilers / SDK
> -- | -- | --
> PHP (beta) | Linux, Mac | PHP 5.5+, PHP 7.0+

While we're at it: are the supported PHP versions accurate?

@stanley-cheung @veblush @donnadionne : can either of you comment on this?

cc @jtattermusch @gnossen

**Comment by stanley-cheung** [comment]
No it's not. `(beta)` should be removed.

**Comment by chalin** [comment]
Thanks for the quick response @stanley-cheung!
