### ISSUE TITLE
Python support for macOS v10.11? Also, is error obsolete?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#516]
@gnossen @lidizheng : This is a followup to _Python: update supported versions to 3.5+, only #514_.

In the [Python Quick start](https://grpc.io/docs/languages/python/quickstart/) one can read:

> On El Capitan OSX, you may get the following error:
> 
> ```sh
> $ OSError: [Errno 1] Operation not permitted: '/tmp/pip-qwTLbI-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
> ```

**Is macOS X El Capitan (v10.11) really still supported?** The current macOS X version is 10.15, and version 11.0 was released today.

Also, that **error is for Python 2.x**, which (if #514 is merged), isn't supported anymore. Might this error still occur under Python 3? If not, can the text quoted above be removed?

cc @jtattermusch

**Comment by chalin** [comment]
From https://github.com/grpc/grpc/pull/24282 I see that macOS 10.10+ are supported, so 10.11 is still ok!

/cc @veblush 

The question that remains is: should anything be done about that error message (e.g., remove it from the docs), which seems to be for Python 2.

**Comment by veblush** [comment]
@chalin 10.10+ is right so El Capitan is still supported. I'm surprised to see Python 2.7 is not dropped from the supported Python version since there are many users using it. (I want to drop it, though) Maybe is this only for OSX?

/cc @lidizheng @gnossen

**Comment by gnossen** [comment]
@chalin I don't believe there's actually anything specific to Python 2 about that error other than that the author of that section of the quickstart happened to be using Python 2 to demonstrate. Regardless, I have never personally seen this problem before nor have I seen any questions about it. I think it's probably safe to remove.

**Comment by chalin** [comment]
Thanks for the feedback @gnossen.

@veblush: From what I recall of my exchange with @gnossen was that Python 3 is officially supported, and Python 2 support is deprecated (not dropped). @gnossen has approved the doc change in which Python 2 was listed in the officially supported versions.

**Comment by chalin** [comment]
> I think it's probably safe to remove.

Done via #554
