### ISSUE TITLE
Links are missing to generated code reference.

### ISSUE THREAD

**Issue by GauntletWizard** [grpc/grpc.io#53]
**Describe the bug**
The reference docs for the code generated by the GRPC Plugins are not linked anywhere from the GRPC site.

**To Reproduce**
1. Go to 'https://grpc.io/docs/reference/'
2. Click on 'Go API'
3. Reference docs are about the base API for establishing GRPC connections, not about code generated by GRPC plugins

**Expected behavior**
Two links - One to https://godoc.org/google.golang.org/grpc, another https://grpc.io/docs/reference/go/generated-code/

**Comment by tuterdust** [comment]
Hi, I already opened PR about this issue (https://github.com/grpc/grpc.io/pull/32)

**Comment by vjpai** [comment]
Cc: @lucperkins

**Comment by muxi** [comment]
Ping for update

**Comment by srini100** [comment]
FYI, the links to generated code can be found in https://grpc.io/docs/
I'll be good to have a separate section in https://grpc.io/docs/reference/ for links to generated code.

**Comment by mingrammer** [comment]
Ping for update

**Comment by lucperkins** [comment]
As noted above, these docs are shown in the site nav: https://grpc.io/docs/reference
