### ISSUE TITLE
Sidenav: show leaf pages under platforms

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#549]
This is what the Platforms sidenav currently looks like (2020/11):

> <img src="https://user-images.githubusercontent.com/4140793/100468878-4af05900-30a3-11eb-93f5-53a5c9365a7a.png" width=200>

It would be nice to be able to show the leaf pages under subsections like **Android > Java**. Of course, one way it to support an extra level of nesting, but maybe there is another way (by anchoring sections). Also, maybe this can be addressed in the context of the docsy migration #479.

cc @aidanranney

**Comment by aidanranney** [comment]
In the Docsy sidebar nav, I believe this should be the default behaviour. The titles of the subsections will differ slightly from these, as they get their titles directly from the associated `_index.md` file in the content folder, but all together it looks something like:
![image](https://user-images.githubusercontent.com/32148529/100470548-4b7df500-308d-11eb-8e66-4beacc31f774.png)
