### ISSUE TITLE
Kotlin: drop "/JVM" from Kotlin language page title

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#573]
Now that grpc.io has a [Platforms](https://grpc.io/docs/platforms/) section, I'd like to propose (for sake of uniformity with other languages, including Dart, that can target different platforms) that we drop the "/JVM" qualifier from the [Kotlin language landing page](https://grpc.io/docs/languages/kotlin/).

Thoughts @lowasser @bshaffer @davidwiner @jamesward?

Original context that gave rise to the introduction of "/JVM": https://github.com/grpc/grpc.io/issues/132#issuecomment-600211694

> @lowasser commented on Mar 17
> It might be worth marking it as "Kotlin/JVM" rather than "Kotlin" generically, though? We are not yet supporting the Javascript or Native compilation backends for Kotlin.

**Comment by jamesward** [comment]
Sounds good to me!
