### ISSUE TITLE
About: define RPC on first use

### ISSUE THREAD

**Issue by roblatour** [grpc/grpc.io#590]
.... gRPC is a modern open source high performance RPC framework that can run in any .... 
document should spell out "RPC" on first use (i.e. what does "RPC" stand for?)

ref: https://www.grpc.io/about/#osp

**Comment by dfawley** [comment]
Is this in an area that you own @chalin?

**Comment by chalin** [comment]
I was planning on looking into it (once I caught up), but feel free to take this issue if you'd like.

**Comment by chalin** [comment]
Thanks for reporting this issue @roblatour.
I've submitted #699 -- can you review it @dfawley?
