### ISSUE TITLE
Heading styles are confusing

### ISSUE THREAD

**Issue by cjyabraham** [grpc/grpc.io#6]
h5 has a smaller font than regular paragraph text.  See [here](http://localhost:1313/docs/guides/auth/) or [here](http://localhost:1313/docs/tutorials/basic/c/).  Can it be made larger and more distinct?  

Also, h2s are still smaller than h3s which is problematic on a page like [this](http://localhost:1313/docs/reference/java/generated-code/).

**Comment by bgguna** [comment]
I can pick up this issue and create a PR. This is going to be my first PR to this community so if anything is incorrect, please shout out.

**Comment by ejona86** [comment]
This appears fixed in the revamp.
