### ISSUE TITLE
page broken. 

### ISSUE THREAD

**Issue by rajibmitra** [grpc/grpc.io#61]
Hi Team, dockerhub mentions this page  https://www.grpc.io/docs/tutorials/basic/c.html but seems like it is broken , let me know if you need any help fixing that. 

Thanks to @brendandburns who originally found this issue.

**Comment by yashykt** [comment]
https://www.grpc.io/docs/tutorials/basic/cpp/ is the actual webpage

**Comment by rajibmitra** [comment]
Thanks @yashykt , closing this issue now.
