### ISSUE TITLE
Retire old grpc.github.io GitHub pages site

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#654]
In March of 2020, some of us were surprised to see that the **old site** ([grpc.github.io](https://grpc.github.io/)) was **still fully hosted on GitHub pages** - https://github.com/grpc/grpc/issues/22294.

At the time we opted to add a this-site-is-obsolete banner containing page-to-page links to the new site.

The new site ([grpc.io](https://grpc.io)) has been up for two years now and the above-mentioned banner on the old site for 11 months. In the interest of reducing technical debt for future website maintainers, I suggest that we retire the old grpc.github.io site.

Any objections? @ejona86 @jtattermusch @srini100 @thisisnotapril 

To be clear, the objective is to retire the GitHub-pages site generated from [github.com/grpc/grpc.github.io](https://github.com/grpc/grpc.github.io), not the gRPC API pages generated from [github.com/grpc/grpc/tree/gh-pages](https://github.com/grpc/grpc/tree/gh-pages), etc.

**Comment by ejona86** [comment]
I don't think the old site was ever actively presented on grpc.github.io (although it would have worked) until after it was replaced. For example, until https://github.com/grpc/grpc.io/pull/80 it was used for serving the release tag.

I'm game for retiring it, although it's not 100% clear to me what that implies since it is just one part of the grpc.github.io website. We may need a basic index.html and robots.txt, for example.

**Comment by chalin** [comment]
> I'm game for retiring it, although it's not 100% clear to me what that implies since it is just one part of the grpc.github.io website. We may need a basic index.html and robots.txt, for example.

Actually, it turns out that it's impossible to retire the GitHub pages site after it's published. What I've done is to publish from a branch that contains only the repo's `README.md`.

As a result, https://grpc.github.io/ shows the README content. So no need for HTML content, or robot files, etc.

I've checked that the API docs aren't impacted, e.g., see https://grpc.github.io/grpc/cpp/

Can we consider this issue closed @ejona86?

**Comment by chalin** [comment]
I might be able to create an index page that could redirect to grpc.io, but I'm not sure that it is worth it. Let me know what you think.

**Comment by ejona86** [comment]
The main vs master is subtle, but LGTM. No need to auto-redirect.

**Comment by chalin** [comment]
Ok, let's consider this fixed. If someone wants something different done, please comment here.

Closed via https://github.com/grpc/grpc.github.io/commit/2b6c94b50d2920208221135f99fb37800e8c6549
