### ISSUE TITLE
SCSS: revert import order of site variables?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#668]
Here's a diff between docsy's and our website's [assets/scss/main.scss](https://github.com/grpc/grpc.io/blob/main/assets/scss/main.scss) file:

> <img src="https://user-images.githubusercontent.com/4140793/108753068-43114b00-7512-11eb-929b-7df7e127f63f.png" width=400>

As far as I can tell, [assets/scss/_variables_project.scss](https://github.com/grpc/grpc.io/blob/main/assets/scss/_variables_project.scss) contains variable overrides that are defined using `!default` in docsy's [variables](https://github.com/google/docsy/blob/master/assets/scss/_variables.scss) file, so it should actually be ok for `variables_project.scss` to be included first, right @aidanranney? If so, why change the order? Is there something I'm missing?

cc @nate-double-u

**Comment by aidanranney** [comment]
@chalin no nothing you're missing! I would chalk this up to a mis-matched order that got in here at some point when the `main.scss` file was introduced as an override [which I see has been removed now in favour of editing the submodule]. After reviewing [the docs](https://sass-lang.com/documentation/variables#default-values) it appears that including the `@import` statement for any custom values first is the way to go, though in testing the site the custom initialization worked in either case.

**Comment by chalin** [comment]
> @chalin no nothing you're missing! I would chalk this up to a mis-matched order that got in here at some point when the `main.scss` file was introduced as an override

Ok, thanks for confirming.

> [which I see has been removed now in favour of editing the submodule]. 

Actually, for a distinct branch over a fork of docsy.

> After reviewing [the docs](https://sass-lang.com/documentation/variables#default-values) it appears that including the `@import` statement for any custom values first is the way to go, though in testing the site the custom initialization worked in either case.

That is my understanding too. (Thanks for that link.)

**Comment by chalin** [comment]
FYI, when I put `@import "variables_project"` back in its place, the styles get changed:

> <img src="https://user-images.githubusercontent.com/4140793/110175314-8d76af80-7dcf-11eb-9e04-292f9d9815b6.png" width=500>

I'm investigating as to why.

**Comment by chalin** [comment]
Actually, the new values are what we want so I'm glad that the import order is getting corrected.

Here is why we are getting different `style.css` files.

- `variables` contains the following definitions:

  ```scss
  $link-color: darken($blue, 15%) !default;
  $link-hover-color: darken($link-color, 15%) !default;
  ```

- `variables_project` has the following override:

  ```scss
  $link-color: #379c9c;
  ```

When `variables_project` is included _after_ `variables` then, in the end, `$link-color` is overridden, but `$link-hover-color` retains its blue-hued color based on its first definition in `variables`.

When `variables_project` is included _before_ `variables` (as it should be) then, in the end, `$link-color` retains its project-specific value (as defined in `variables_project`) and `$link-hover-color` gets computed from this project-specific value -- which is what we want. This is a natural consequence of the [imperative nature of variable assignment in Sass](https://sass-lang.com/documentation/variables).

cc @zacharysarah
