### ISSUE TITLE
Use go install over go get?

### ISSUE THREAD

**Issue by mcculleydj** [grpc/grpc.io#682]
For the Go quick start docs (https://grpc.io/docs/languages/go/quickstart/) you'll find this cmd line snippet to install the binaries necessary to compile .proto into the gRPC Go code and the Protobuf Go code:

```
$ export GO111MODULE=on  # Enable module mode
$ go get google.golang.org/protobuf/cmd/protoc-gen-go \
         google.golang.org/grpc/cmd/protoc-gen-go-grpc
```

This documentation (https://developers.google.com/protocol-buffers/docs/reference/go-generated) recommends using `go install`. Also the 1.16 release notes section on modules (https://tip.golang.org/doc/go1.16#modules) seems to indicate that Go is moving away from `go get`. Definitely not an expert here, which is why this is an issue/question and not a PR. My sense is that it may depend on which version of Go you have installed. Maybe adding an additional block to the documentation and distinguishing between Go versions makes the most sense?

**Comment by chalin** [comment]
Thanks for your question. @dfawley, any comments?
