### ISSUE TITLE
SCSS: why redefine $gray-100?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#703]
Bootstrap provides variable names for colors like `$white` and `$blue` as well as shades of gray like `$gray-100` to `$gray-900`, see [Color][]. To quote that page:

> [Bootstrap defines] An expansive set of gray variables and a Sass map in `scss/_variables.scss` for consistent shades of gray across your project.

Why then redefine `$gray-100`:
> https://github.com/grpc/grpc.io/blob/a894e6ca5f9759d68b1180d49d46f590c5c13fd9/assets/scss/_variables_project.scss#L5

Won't this break the gray scale? I guess I could ask the question another way: why redefine only one value in that scale as opposed to rebalancing the entire scale?

cc @nate-double-u @zacharysarah 

[Color]: https://getbootstrap.com/docs/4.1/getting-started/theming/#color

**Comment by chalin** [comment]
Asking this another way: shouldn't we be redefining variable(s) like `$link-color` rather than a color value like `$gray-100` (or `$white` or `$blue`)?

**Comment by aidanranney** [comment]
@chalin that's a great point - I'm not sure/can't recall anymore why this value was overridden, but from a global search on the code:
- It appears that it's used internally in Docsy on`pre` elements and a `.pageinfo` class internally in Docsy
- A `.bg-gray-100` utility class and an `.o-banner` class on the grpc side of things.

From a subjective point of view, the default `#f8f9fa` value appears to suit its use very well and it might be worth considering simply removing the overriding line 5 from `_variables_project.scss`? Here's a screenshot comparison with `.bg-gray-100`:

**#f8f9fa**
![image](https://user-images.githubusercontent.com/32148529/110823612-23cf2900-8247-11eb-8af2-c4f08f328e64.png)

**#fafafa**
![image](https://user-images.githubusercontent.com/32148529/110823704-39dce980-8247-11eb-9855-b83abc4db51b.png)

**Comment by chalin** [comment]
Thanks for the explanation.

> simply removing the overriding line 5 from `_variables_project.scss`?

Yes, will do!
