### ISSUE TITLE
Reading server initial metadata in client before sending client request data

### ISSUE THREAD

**Issue by ronf** [grpc/grpc.io#726]
With the Python grpclib library, it's possible to initiate a request on a stream, send some client invocation metadata, and then read the server's initial metadata response BEFORE sending any client request data. This allows the client to vary its request data based on the server's metadata response.

In the grpc library, I wasn't able to find anything equivalent. From what I can see, the sending of the client's invocation metadata is triggered by the creation of a stub's method object, but that object also takes the request information (or an iterator used to supply that information in the case of a streaming request). As such, there doesn't seem to be a way to read back the server's initial response metadata before providing that request data.

Is there a way on a client to create a request and send/receive metadata prior to supplying the request data?

Here's what this looks like with grpclib:

```python
            async with stub.ProcessRequest.open(metadata=metadata) as stream:
                await stream.send_request()

                await stream.recv_initial_metadata()
                print('Initial metadata:', dict(stream.initial_metadata))

                for request in request_iter():
                    await stream.send_message(request)

                await stream.end()

                async for response in stream:
                    pass    # Process response data

                await stream.recv_trailing_metadata()
                print('Trailing metadata:', dict(stream.trailing_metadata))
```

**Comment by yashykt** [comment]
https://groups.google.com/g/grpc-io or stack-overflow are the proper avenues for questions like these.

I'm closing this pre-emptively and tagging @gnossen for a potential post-close answer

**Comment by lidizheng** [comment]
@ronf For unary RPCs, gRPC currently doesn't have a mechanism allowing the application to read the server initial_metadata before sending any requests.

It's true that Core abstracts RPC in 6 different operations, which means technically we can split the receive and send for unary calls. But we don't currently have a solid use case for it. If the application needs to send information in steps, streaming RPCs might be a better answer.

But for stream RPCs, for the logic provided in the snippet, I think gRPC Python AsyncIO API can achieve the same functionality:

```python
stream = stub.RecordRoute(metadata=metadata)
await stream.write(request0)

server_metadata = await stream.initial_metadata()
await stream.write(request1)
await stream.write(request2)
await stream.done_writing()

for message in stream:
    pass # Process the responses

trailing_metadata = await stream.trailing_metadata()
```

Supplying a custom request iterator to gRPC Python API (sync API) can also achieve this:

```python
class RequestIterator:

    def __init__(self):
        self._queue = queue.Queue()

    def send(self, message):
        self._queue.put(message)

    def __iter__(self):
        return self

    def __next__(self):
        return self._queue.get(block=True)

request_iterator = RequestIterator()
response_iterator = stub.StreamingHi(request_iterator)

metadata = request_iterator. initial_metadata()
# Process the initial_metadata from server-side

# In sending thread
request_iterator.send(proto_message)

# In receiving thread
for response in response_iterator:
    process(response)
```
