### ISSUE TITLE
Get PR reviewed and merged

### ISSUE THREAD

**Issue by dcalvin** [grpc/grpc.io#73]
Hi there,
I am from PingCAP. Recently I just opened a PR https://github.com/grpc/grpc.io/pull/68 to add PingCAP use case to the gRPC website. But there seems to no furthering actions happening to this PR. Can someone review or let me know if I did this rightly? Thanks.

**Comment by srini100** [comment]
I left a comment. PTAL.

**Comment by chalin** [comment]
Closing. Track progress on #68 through the PR itself.
