### ISSUE TITLE
Outdated PHP Quickstart Documentation for Protoc

### ISSUE THREAD

**Issue by stemis** [grpc/grpc.io#742]
The documentation here is outdated and is no longer working:
https://grpc.io/docs/languages/php/quickstart/#php-protoc-plugin

For example, running the following:
```
$ git clone -b v1.35.0 https://github.com/grpc/grpc
$ cd grpc
$ git submodule update --init
$ make grpc_php_plugin
```
results in:
`make: *** No rule to make target 'grpc_php_plugin'.  Stop.`

After a while I found the right documentation at: https://github.com/grpc/grpc/blob/master/src/php/README.md#grpc_php_plugin-protoc-plugin

**Comment by veblush** [comment]
@stanley-cheung PTAL

**Comment by lidizheng** [comment]
@stanley-cheung PTAL
