### ISSUE TITLE
Introduction points to  github.com/golang/protobuf instead of  pkg.go.dev/google.golang.org/protobuf

### ISSUE THREAD

**Issue by aperrot42** [grpc/grpc.io#768]
Hi, it seems like the introduction page : https://grpc.io/docs/what-is-grpc/introduction/
Points to oldish https://github.com/golang/protobuf. Souldn't it point to https://pkg.go.dev/google.golang.org/protobuf instead ?

(I've seen many people from my team doing first time installation and using the old version of protobuff).

**Comment by chalin** [comment]
@dfawley - comments?

**Comment by dfawley** [comment]
SGTM.  The old library is now deprecated, even though we continue to use it internally and in some of our APIs in gRPC-Go.  The new library should be completely interoperable, though, and we might as well point users to it.

**Comment by chalin** [comment]
@aperrot42 - might you be willing to submit a PR? Thanks.

**Comment by aperrot42** [comment]
Alright will do tomorrow, thanks !

**Comment by aperrot42** [comment]
Sorry @dfawley  & @chalin did not take the time for this simple PR. Had some time to do do it quickly this morning : https://github.com/grpc/grpc.io/pull/791 Please let me know if it seems correct whenever you can. Good day.

**Comment by chalin** [comment]
Thanks again for the PR! Have a good day too.
