### ISSUE TITLE
C++ basics tutorial contains a broken link to CMakeLists.txt

### ISSUE THREAD

**Issue by jonathan-o** [grpc/grpc.io#771]
There's a broken link in the tutorial document. It refers to a CMakeLists.txt file (https://github.com/grpc/grpc/blob/v1.35.0/examples/cpp/route_guide/CMakeLists.txt) for compiling the project. The link results in a 404 error, and the file is also not present in the example repository. I cannot proceed with the tutorial because the file doesn't exist.

**Comment by drfloob** [comment]
Apologies, the docs link to v1.35.0 of the main gRPC core repo, but the CMakeLists.txt file was added in v1.36.0. I'll make sure the docs get updated. In the meantime, you can find the CMakeLists file here: https://github.com/grpc/grpc/blob/v1.36.0/examples/cpp/route_guide/CMakeLists.txt
