### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by Gabreilriley** [grpc/grpc.io#792]
Hey some colleagues from Paris were trying to register on eBMS through the app and it doesn't work well. Specifically, French people try to register and the app gives the message that the account was already registered when it was not the case. Now the users are blocked.

I tried to register another email account from my phone and the website on [ryobi universal router table](https://www.tabletypes.com/best-powered-ryobi-router-table-plans-in-australia/) allows me to do it but I didn't receive the confirmation email so the account is block now and I cannot log in on the app then. Could you check what is happening? Thanks

**Comment by nicolasnoble** [comment]
Totally wrong github repository.

**Comment by nicolasnoble** [comment]
Also, spam, actually. Reporting.
