### ISSUE TITLE
Benchmark dashboard is broken

### ISSUE THREAD

**Issue by ahmetb** [grpc/grpc.io#793]
Benchmark docs at https://grpc.io/docs/guides/benchmarking/ links to dashboard https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5180705743044608

This dashboard is broken and not loading any data. Warnings tab is full of errors.

![image](https://user-images.githubusercontent.com/159209/120224551-8574b300-c1f8-11eb-86e4-98f64725fdda.png)

**Comment by ahmetb** [comment]
This is likely an issue with the dashboard software running on iOS Safari. It worked fine on a Chrome desktop browser.

**Comment by jtattermusch** [comment]
At some point we should improve the UI of the dashboard (at this point it does the job, but it could be more useful).
Currently the UI is based on PerfKit explorer, which isn't being developed anymore.
