### ISSUE TITLE
Website issue - Deprecated envoy code in grpc web tutorial

### ISSUE THREAD

**Issue by 4br3mm0rd** [grpc/grpc.io#795]
**Issue description**
The envoy code in [grpc-web basics](https://grpc.io/docs/platforms/web/basics/) is deprecated (using xDS v2). Should be replaced by the updating code [https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml](here)

**Comment by dfawley** [comment]
@wenbozhu this is a grpc-web example - can you take a look / reassign please?

**Comment by lidizheng** [comment]
Ping @wenbozhu

**Comment by wenbozhu** [comment]
@4br3mm0rd  Thanks! 

Could you help copy the issue to grpc/grpc-web and we will work on the fix?
