### ISSUE TITLE
c++ unary API performance profiling (slow!!!)

### ISSUE THREAD

**Issue by suresh8447** [grpc/grpc.io#802]
We are planning to migrate our project from CORBA into GRPC and as part of the same i am trying to profile API performance and found that CORBA seems to be faster than GRPC.

**Environment details, Windows client and Linux Server**

As prototype tried prototype in CORBA and GRPC using simple API call sequentially (1 client 1 thread vs 1 server 1 thread) and observed grpc API call is 10ms slower than CORBA.

We are also unable to find good document for the performance bench mark created by GRPC https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5180705743044608. We are not able to run the test suit in our environment to see the performance result out of GRPC test suits.

Here is GRPC sample we are using
[Sample.zip](https://github.com/grpc/grpc.io/files/6763642/Sample.zip)

Please let me know if any further info required for this and help improving the performance numbers.

**Comment by veblush** [comment]
This place is not a good to discuss performance, could you use https://github.com/grpc/grpc instead? And it's useful to know more about gRPC version, platform version, etc. And probably it'd be nice to try local connection first to verify whether the benchmark environment is properly set up. It's not common to see 10ms delay in the local network, though.

**Comment by chalin** [comment]
Closing this issue based on @veblush's recommendation. As suggested, consider reopening over grpc/grpc, or post to one of the forums listed under https://grpc.io/community/.
