### ISSUE TITLE
A bug in PHP bidirectional streaming example

### ISSUE THREAD

**Issue by lebedevsergey** [grpc/grpc.io#811]
Seems that there's a bug in documentation [here](https://grpc.io/docs/languages/php/basics/#streaming-rpcs)

    foreach ($notes as $n) {
      $route_note = new Routeguide\RouteNote();
      $call->write($route_note);
    }
    $call->writesDone();`

This code doesn't use `$n` variable in any way, it just sends an empty `RouteNote`

**Comment by ejona86** [comment]
Fixed by #834
