### ISSUE TITLE
API references redirect to archived grpc.github.io

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#86]
Several API reference links direct to grpc.github.io, but that repo (https://github.com/grpc/grpc.github.io) has been **archived**.

**To Reproduce**
1. Visit https://grpc.io/docs/reference
2. Click on the **C++ API** reference.
3. A new tab will open over https://grpc.github.io/grpc/cpp/index.html

Maybe it would be preferable (as is done for the Go API), to link to an external site?

**Comment by chalin** [comment]
@thisisnotapril @nicolasnoble @lucperkins @jtattermusch any comment on this?

**Comment by chalin** [comment]
@srini100, this came up during the sync meeting. Any comment about this? /cc @dwiner

**Comment by srini100** [comment]
I believe the eventual content of the API reference pages that is getting redirected to grpc.github.io is coming from grpc/grpc repo's gh-pages branch. gh-pages is one way to host the docs for a given repo but I do not know how grpc.github.io is mapped to that.

**Comment by chalin** [comment]
Ah, right. The GitHub Pages repo is off of the grpc/grpc gh-pages branch: https://github.com/grpc/grpc/tree/gh-pages.

Closing this issue since the grpc.github.io repo isn't actually being used.
