### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dvidx** [grpc/grpc.io#872]
When using TLS-based authentication the server url must not be an ip address. 
While a deprecation warning is thrown _([DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.)_ it is not obvious that this is the actual reason that a connection can not be established.

This is also means that when testing locally with server url **'0.0.0.0' won't work**. 
But using **'localhost' does**.
Since this behavior is neither obvious nor logic (in my opinion) I propose using 'localhost' instead of '0.0.0.0' in the documentation, and also adding a note to the authentication guide, informing that a non ip address value is required for the server name.

**Comment by ejona86** [comment]
@murgatroid99, seems I don't have enough permissions to move this to the grpc-node repo. But I expect you do.

**Comment by murgatroid99** [comment]
I don't have permissions to move issues out of this repository. I don't even have a "Transfer issue" button.

**Comment by ejona86** [comment]
Ugh. I guess that means you have to have write access to both the source and destination. I can see why that is necessary, but it does make transferring less useful.

@murgatroid99, since we can't transfer, would you recommend @dvidx to open an issue on grpc-node and cross-link it to this one?

**Comment by murgatroid99** [comment]
I think that would be the best way we have to handle this.

Alternatively, I can just mention that the Node libraries support the `grpc.ssl_target_name_override` channel option, just like the core-based libraries. Then maybe this issue is fully addressed.

**Comment by dvidx** [comment]
First of all thank you for your help @ejona86 and @murgatroid99.

Both the Quickstart-Guide [https://grpc.io/docs/languages/node/quickstart/#update-the-server](url) and the Basic Tutorial [https://grpc.io/docs/languages/node/basics/#starting-the-server](url) use 0.0.0.0 in their examples. 

I agree with all the points you listed. This should never be an issue in real world case. 
It is simply confusing when testing the TLS implementation locally at least as someone new to gRPC.

Just to be clear again, my issue is that when trying to run with 0.0.0.0, I get the following message: 
> (node:32879) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> Error: 14 UNAVAILABLE: No connection established
 
It does let me know I shouldn't use an IP address but I would still expect it to work since it is "just" a deprecation warning, therefore I was falsely looking for the issue in another place.

**Comment by dvidx** [comment]
Opened a new issue on grpc-node: [https://github.com/grpc/grpc-node/issues/1919](url)

**Comment by ejona86** [comment]
Closing, since 0.0.0.0 is for binding and don't impact the TLS message at all, so the docs seem correct. Further discussion will happen on the grpc-node repo.
