### ISSUE TITLE
Blog and Docs navbar entries are not shown as active when section pages are being viewed

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#895]
- [ ] Blog: for a screenshot, see below - #896
- [ ] Docs

<img width="929" alt="Screen Shot 2021-11-09 at 4 12 28 PM" src="https://user-images.githubusercontent.com/4140793/141005563-3b402a29-47e6-40e5-9caf-ca1a973217e9.png">

**Comment by chalin** [comment]
@nate-double-u: I think that our other sites might suffer from the same problem.

**Comment by nate-double-u** [comment]
I am seeing it on our other sites. We should link this issue to [etcd](https://github.com/etcd-io/website/) and [notaryproject](https://github.com/notaryproject/notaryproject.dev). I'll open issues there too (and PRs, looks like you've found a good solution).
