### ISSUE TITLE
Quick start - Command issue

### ISSUE THREAD

**Issue by gozeloglu** [grpc/grpc.io#903]
Hi. I was trying to run [Go/Quick Start](https://grpc.io/docs/languages/go/quickstart/#run) document examples, but I got an error when I run the code. As the documentation says that I run the client code with the following command, but I got different output. It prints out [`defaultName`](https://github.com/grpc/grpc-go/blob/c2bccd0b1594416da57a74d15f09f8eb0a3d727b/examples/helloworld/greeter_client/main.go#L33).
```bash
$ go run greeter_client/main.go Alice 
2021/12/01 10:43:14 Greeting: Hello world
2021/12/01 10:43:14 Greeting: Hello again world
```
But, the documentation says that it needs to print out **Alice**. So, I changed the command and run it again, then it prints out as we expected.
```bash
 $  go run greeter_client/main.go --name=Alice 
2021/12/01 10:43:16 Greeting: Hello Alice
2021/12/01 10:43:16 Greeting: Hello again Alice
```

So, I think the documentation needs to be changed with the `--name` flag. If it is OK for you, I can fix it.

**Comment by dapengzhang0** [comment]
@menghanl, @easwars, @zasweq

**Comment by easwars** [comment]
@gozeloglu 
At some point, we changed our examples to use flags instead of positional arguments since the former was more idiomatic Go. It would be much appreciated if you send a PR to fix the documentation. Thank you.

**Comment by gozeloglu** [comment]
Hi @easwars. I'll send PR as soon as possible. Thanks for your response.
