### ISSUE TITLE
Basics tutorial - CI/CD testing for bidirectional streams for NodeJS

### ISSUE THREAD

**Issue by westandy** [grpc/grpc.io#906]
I am trying to find any examples of using this anywhere out there.  Before with unary calls, I was able to start a Service within a Jest framework, run client unary calls against that service and verify (`expect`) calls and data.  With bidirectional streams, I can start the service, and a client, but it is as if the streams do not run until I shut down the service.  And then Jest complains that I left a process running.  I would love to see an example of how to do this.   Even if it's mocha/chai/jest/whatever.  Thank you!

**Comment by dapengzhang0** [comment]
This seems a gRPC technical question, not really a community/gRPC.io website question. Can you please ask the question in the https://groups.google.com/g/grpc-io or file an issue at https://github.com/grpc/grpc, where people can likely help, and close the issue here?
