### ISSUE TITLE
Dart examples fail to build after recompiling proto file

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#92]
The quick start and tutorial examples depend on the [protoc_plugin v18](https://pub.dev/packages/protoc_plugin#1803), which, when guides were written, was the latest version.

Since then, [v19](https://pub.dev/packages/protoc_plugin#1900) has been released, but this version introduces breaking changes and requires [protobuf v1.x](https://pub.dev/packages/protobuf#101).

So either the guides need to be updated to:
- Constrain the version of `protoc_plugin` that is downloaded to be `< 19`, or
- Example pubspecs need to be updated to use [protobuf v1.x](https://pub.dev/packages/protobuf#101).

**Comment by chalin** [comment]
https://github.com/grpc/grpc-dart/pull/279 updates the protobuf version.

**Comment by menghanl** [comment]
@lucperkins Can you take a look?

**Comment by chalin** [comment]
Btw, this issue is resolved by https://github.com/grpc/grpc-dart/pull/279. If the merge of 279 is delayed, then the quick start and tutorial can be tweaked to download v18 of the plugin.

**Comment by chalin** [comment]
Closed by https://github.com/grpc/grpc-dart/pull/279
