### ISSUE TITLE
Cooperation invitation from Apache APISIX community

### ISSUE THREAD

**Issue by yzeng25** [grpc/grpc.io#932]
Hi folks,

I am Yilin, from the Apache APISIX community. Apache APISIX is a Cloud-native API gateway, and it is the top-level project of the Apache Software Foundation. You can get more details from our GitHub repository[1].

We have developed a plugin named "grpc-web"[2] to integrate grpc-web with Apache APISIX. I think the plugin is very meaningful for developers and both communities. In addition, it will help grpc-web and Apache APISIX publicize and let more developers and companies know about us.

Are you interested in posting this article[3] on your website's blog[4] or some other places?

Thanks!

[1] https://github.com/apache/apisix
[2] https://github.com/apache/apisix/pull/5964
[3] https://apisix.apache.org/blog/2022/01/25/apisix-grpc-web-integration
[4] https://grpc.io/blog/

**Comment by stanley-cheung** [comment]
cc @sampajano

**Comment by sampajano** [comment]
Hi! Thanks for the request! May we continue the discussion in https://github.com/grpc/grpc-web/discussions/1185?

Thanks! :)

**Comment by yzeng25** [comment]
> 

Sure!
