### ISSUE TITLE
macos clang address sanitizer use in Debug mode crash in FillMetadataArray

### ISSUE THREAD

**Issue by IgorV-fp** [grpc/grpc.io#935]
When use macos clang with address sanitizer feature in Debug mode - grpc crash in FillMetadataArray call.

Suggested fix (tested in our product, which use grpc 1.43.0):
initialize all pointers to nullptr in class member definition (call_op_set.h and interceprot_common.h)
add to FillMetadataArray function:
if (*metadata_count >= UINT_MAX)
  {
      std::cerr << std::endl << "Error in FillMetadataArray: metadata count is more than UINT_MAX! "
                << *metadata_count << "/" << UINT_MAX << std::endl;
      *metadata_count = 0;
      return nullptr;
  }

**Comment by markdroth** [comment]
This is the wrong place to file this issue.  Please file this issue in https://github.com/grpc/grpc instead.
