### ISSUE TITLE
C++ quick start issues

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#94]
From https://groups.google.com/d/msgid/grpc-io/a13d4456-fbb6-4b89-922f-69672804a07f%40googlegroups.com:
> 1) https://grpc.io/docs/quickstart/cpp/ says "follow the instructions to install gRPC C++ via make", but the linked page leads with bazel (with a secondary reference to cmake).
> 2) The linked page: https://github.com/grpc/grpc/blob/master/src/cpp/README.md#make doesn't work. I think it may be because http_archive has been moved/deprecated but the rules don't include the relevant spell to import it - see https://stackoverflow.com/questions/56229865/build-breaking-after-bazel-upgrade

@nicolasnoble writes:
> We should direct people towards Bazel as much as possible for the quickstart, especially since the ./tools/bazel script should be fine for Linux and windows even if Bazel isn't installed. 

cc @thisisnotapril

**Comment by muxi** [comment]
@nicolasnoble - office hour ping/cc

**Comment by chalin** [comment]
Addressed by #96 and #97. Closing.
