### ISSUE TITLE
Missing link - Introduction to gRPC

### ISSUE THREAD

**Issue by techmaharaj** [grpc/grpc.io#944]
"_If you’re new to gRPC and/or protocol buffers, **read this**!_" - missing link on anchor text for read this.
Page: https://grpc.io/docs/what-is-grpc/introduction/

**Comment by sanjaypujare** [comment]
I think it just means "read this article" so there is no missing link. Feel free to open a PR to improve the wording - to say something like "If you’re new to gRPC and/or protocol buffers, then this article is for you!"
