### ISSUE TITLE
c++ quickstart instructions refer only to make, but then point at a doc for bazel

### ISSUE THREAD

**Issue by philipmulcahy** [grpc/grpc.io#95]
https://grpc.io/docs/quickstart/cpp/ says "follow the instructions to install gRPC C++ via make", but the [linked page](https://github.com/grpc/grpc/blob/master/src/cpp/README.md#make) leads with bazel (with a secondary reference to cmake).

**Comment by philipmulcahy** [comment]
I've got a lot further now.
My goal was to run the c++ helloworld example.
I switched from os-x to a clean (patched) install of ubuntu 18.04 on vmware.
In order for g```rpc_cpp_plugin``` to be installed, you need to run ```sudo make install`` in the root of grpc.

This instruction appears to be missing - make install IS referred to in relation to the protobuf submodule but not grpc.
There are various tickets (closed) on this problem, but it seems as if it has not been fixed in the docs yet.

**Comment by muxi** [comment]
@srini100 - office hour ping/cc

**Comment by chalin** [comment]
See #172.
