### ISSUE TITLE
Message Request

### ISSUE THREAD

**Issue by CNX-845589-00003-15455** [grpc/grpc.io#951]
// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

**Comment by sergiitk** [comment]
The message body is a carbon copy of the Quick Start example. I have all reasons to believe this message is a spam.
