### ISSUE TITLE
Examples: add `--shallow-submodules` to clone command

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#955]
@gnossen wrote:

>> While you're at it, you might want to add `--shallow-submodules`:
>
> Sure, I can do that in my next PR. We only want this for `grpc/grpc`, right?

_Originally posted by @chalin in https://github.com/grpc/grpc.io/issues/954#issuecomment-1076620106_

**Comment by gnossen** [comment]
To my knowledge, `grpc/grpc` is the only repo that uses submodules, yes.

**Comment by chalin** [comment]
For context, this was in support of https://github.com/open-telemetry/opentelemetry.io/pull/1224.
