### ISSUE TITLE
c++ bazel instructions don't work

### ISSUE THREAD

**Issue by philipmulcahy** [grpc/grpc.io#96]
https://github.com/grpc/grpc/blob/master/src/cpp/README.md#make
It looks like bazel has had a non-backwards compatible upgrade since this page was written - the http_archive rule needs to be imported/included.
I got it working by adding 
```load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")```

Additionally and on a less technical front,  it'd probably be worth explaining:
* that the example code needs to be in a WORKSPACE file
* how to choose a grpc version

At the moment, there are significant unnecessary barriers to  grpc newbies: you/we are telling them to use bazel, which they may never have used before, but expecting them to know how to use bazel already. You/we are also assuming they know which commit hash they should be using.

**Comment by philipmulcahy** [comment]
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "c2ab8a42a0d673c1acb596d276055adcc074c1116e427f118415da3e79e52969",
    strip_prefix = "grpc-1.27.3",
    urls = [
        "https://github.com/grpc/grpc/archive/v1.27.3.tar.gz"
    ],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
```
Seems to work.
I chose 1.2.73 from https://github.com/grpc/grpc/releases (latest non pre-release).
I got the sha256 by wgetting the url and then doing sha256sum on it.
It's a bit messy that curl doesn't easily work on such github links, presumably due to 302 redirects.
If you don't include it in the above config, bazel prompts/pesters you to make your build repeatable/safe (seems sensible).
I'm not sure how I could have fished the sha256 out of github without doing the initial fetch.

**Comment by muxi** [comment]
@veblush - office hour cc/ping

**Comment by veblush** [comment]
Thanks for the report. I'll close this issue since you managed to build it with bazel but I'll come up with the better documentation with https://github.com/grpc/grpc/issues/22419.
