### ISSUE TITLE
protobuf build/install instructions broken

### ISSUE THREAD

**Issue by philipmulcahy** [grpc/grpc.io#97]
https://grpc.io/docs/quickstart/cpp/ directs users to build protobufs by using make.
There are two problems with this:
1) protobufs are a submodule - I reckon not everyone knows how to clone a repo WITH the submodules
2) there's no Makefile - it looks like it's been moved over to bazel

**Comment by muxi** [comment]
@nicolasnoble - office hour cc/ping

**Comment by chalin** [comment]
See #172.
