### ISSUE TITLE
Generated-code reference: link to deprecated package; different one than quick start

### ISSUE THREAD

**Issue by hut8** [grpc/grpc.io#973]
The first link on https://grpc.io/docs/languages/go/generated-code/ is to 
https://godoc.org/github.com/golang/protobuf/protoc-gen-go/grpc -- this specifically says that it's deprecated, it can be removed, and not to use it. In fact it looks like the entire module github.com/golang/protobuf has been deprecated:

> It has been superseded by the [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf) module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the google.golang.org/protobuf module.

Is it possible that https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc is what you actually would want? On https://grpc.io/docs/languages/go/quickstart/ it specifically references these packages and the paths look very similar although the APIs are different.

So on "Quick Start", it references the non-deprecated package, but on Generated Code Reference, it seems to give documentation for a different code generation package. Am I missing something?

**Comment by sergiitk** [comment]
@dfawley friendly ping

**Comment by dfawley** [comment]
Yes, the link should be updated to point to the new codegen tool.
