### ISSUE TITLE
Add a case-studies part on grpc.io

### ISSUE THREAD

**Issue by remyleone** [grpc/grpc.io#99]
It would be a good idea to have a part of the website reserved for testimonies and case studies such as the one on Kubernetes: https://kubernetes.io/case-studies/

It could feature use-cases from:

- Netflix
- etcd
- Kubernetes
- Dropbox

With external links. At the moment, there is a "Used by" on the main page but not any link towards a use-case.

**Comment by muxi** [comment]
@srini100 - office hour ping

**Comment by dapengzhang0** [comment]
Office hour ping. This issue is not active over two weeks.
cc @srini100 @thisisnotapril

**Comment by srini100** [comment]
Assigning to @chalin to see if this is feasible.

**Comment by chalin** [comment]
Good idea @remyleone. We'll track this request via #206.
